// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: services/mail-service/proto/mail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateAccountRequest represents a request to create an account
type CreateAccountRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FirstName            string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BirthDate            string                 `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender               string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PreferredCountry     string                 `protobuf:"bytes,5,opt,name=preferred_country,json=preferredCountry,proto3" json:"preferred_country,omitempty"`
	UsePhoneVerification bool                   `protobuf:"varint,6,opt,name=use_phone_verification,json=usePhoneVerification,proto3" json:"use_phone_verification,omitempty"`
	CustomEmailPrefix    string                 `protobuf:"bytes,7,opt,name=custom_email_prefix,json=customEmailPrefix,proto3" json:"custom_email_prefix,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAccountRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateAccountRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateAccountRequest) GetPreferredCountry() string {
	if x != nil {
		return x.PreferredCountry
	}
	return ""
}

func (x *CreateAccountRequest) GetUsePhoneVerification() bool {
	if x != nil {
		return x.UsePhoneVerification
	}
	return false
}

func (x *CreateAccountRequest) GetCustomEmailPrefix() string {
	if x != nil {
		return x.CustomEmailPrefix
	}
	return ""
}

// CreateAccountResponse represents the response to account creation
type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetAccountRequest represents a request to get an account
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Account represents a mail account
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount    int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Account) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Account) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Account) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Account) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Account) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Account) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// ListAccountsRequest represents a request to list accounts
type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAccountsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAccountsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// AccountList represents a list of accounts
type AccountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountList) Reset() {
	*x = AccountList{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountList) ProtoMessage() {}

func (x *AccountList) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountList.ProtoReflect.Descriptor instead.
func (*AccountList) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{5}
}

func (x *AccountList) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateAccountStatusRequest represents a request to update account status
type UpdateAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountStatusRequest) Reset() {
	*x = UpdateAccountStatusRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountStatusRequest) ProtoMessage() {}

func (x *UpdateAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateAccountStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// UpdateAccountStatusResponse represents the response to status update
type UpdateAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountStatusResponse) Reset() {
	*x = UpdateAccountStatusResponse{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountStatusResponse) ProtoMessage() {}

func (x *UpdateAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RetryRegistrationRequest represents a request to retry registration
type RetryRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRegistrationRequest) Reset() {
	*x = RetryRegistrationRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRegistrationRequest) ProtoMessage() {}

func (x *RetryRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRegistrationRequest.ProtoReflect.Descriptor instead.
func (*RetryRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{8}
}

func (x *RetryRegistrationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// RetryRegistrationResponse represents the response to retry request
type RetryRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRegistrationResponse) Reset() {
	*x = RetryRegistrationResponse{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRegistrationResponse) ProtoMessage() {}

func (x *RetryRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRegistrationResponse.ProtoReflect.Descriptor instead.
func (*RetryRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{9}
}

func (x *RetryRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteAccountRequest represents a request to delete an account
type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// DeleteAccountResponse represents the response to delete request
type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetStatisticsRequest represents a request to get statistics
type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{12}
}

// Statistics represents service statistics
type Statistics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalAccounts    int64                  `protobuf:"varint,1,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	AccountsByStatus map[string]int64       `protobuf:"bytes,2,rep,name=accounts_by_status,json=accountsByStatus,proto3" json:"accounts_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SuccessRate      float32                `protobuf:"fixed32,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageRetries   float32                `protobuf:"fixed32,4,opt,name=average_retries,json=averageRetries,proto3" json:"average_retries,omitempty"`
	LastHour         int64                  `protobuf:"varint,5,opt,name=last_hour,json=lastHour,proto3" json:"last_hour,omitempty"`
	Last_24Hours     int64                  `protobuf:"varint,6,opt,name=last_24_hours,json=last24Hours,proto3" json:"last_24_hours,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_services_mail_service_proto_mail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_services_mail_service_proto_mail_proto_rawDescGZIP(), []int{13}
}

func (x *Statistics) GetTotalAccounts() int64 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *Statistics) GetAccountsByStatus() map[string]int64 {
	if x != nil {
		return x.AccountsByStatus
	}
	return nil
}

func (x *Statistics) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *Statistics) GetAverageRetries() float32 {
	if x != nil {
		return x.AverageRetries
	}
	return 0
}

func (x *Statistics) GetLastHour() int64 {
	if x != nil {
		return x.LastHour
	}
	return 0
}

func (x *Statistics) GetLast_24Hours() int64 {
	if x != nil {
		return x.Last_24Hours
	}
	return 0
}

var File_services_mail_service_proto_mail_proto protoreflect.FileDescriptor

const file_services_mail_service_proto_mail_proto_rawDesc = "" +
	"\n" +
	"&services/mail-service/proto/mail.proto\x12\x04mail\"\x9c\x02\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12+\n" +
	"\x11preferred_country\x18\x05 \x01(\tR\x10preferredCountry\x124\n" +
	"\x16use_phone_verification\x18\x06 \x01(\bR\x14usePhoneVerification\x12.\n" +
	"\x13custom_email_prefix\x18\a \x01(\tR\x11customEmailPrefix\"\x8d\x01\n" +
	"\x15CreateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xd4\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\"[\n" +
	"\x13ListAccountsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"N\n" +
	"\vAccountList\x12)\n" +
	"\baccounts\x18\x01 \x03(\v2\r.mail.AccountR\baccounts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"x\n" +
	"\x1aUpdateAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"7\n" +
	"\x1bUpdateAccountStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x18RetryRegistrationRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"5\n" +
	"\x19RetryRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"1\n" +
	"\x15DeleteAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14GetStatisticsRequest\"\xdb\x02\n" +
	"\n" +
	"Statistics\x12%\n" +
	"\x0etotal_accounts\x18\x01 \x01(\x03R\rtotalAccounts\x12T\n" +
	"\x12accounts_by_status\x18\x02 \x03(\v2&.mail.Statistics.AccountsByStatusEntryR\x10accountsByStatus\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x02R\vsuccessRate\x12'\n" +
	"\x0faverage_retries\x18\x04 \x01(\x02R\x0eaverageRetries\x12\x1b\n" +
	"\tlast_hour\x18\x05 \x01(\x03R\blastHour\x12\"\n" +
	"\rlast_24_hours\x18\x06 \x01(\x03R\vlast24Hours\x1aC\n" +
	"\x15AccountsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\x86\x04\n" +
	"\vMailService\x12H\n" +
	"\rCreateAccount\x12\x1a.mail.CreateAccountRequest\x1a\x1b.mail.CreateAccountResponse\x124\n" +
	"\n" +
	"GetAccount\x12\x17.mail.GetAccountRequest\x1a\r.mail.Account\x12<\n" +
	"\fListAccounts\x12\x19.mail.ListAccountsRequest\x1a\x11.mail.AccountList\x12Z\n" +
	"\x13UpdateAccountStatus\x12 .mail.UpdateAccountStatusRequest\x1a!.mail.UpdateAccountStatusResponse\x12T\n" +
	"\x11RetryRegistration\x12\x1e.mail.RetryRegistrationRequest\x1a\x1f.mail.RetryRegistrationResponse\x12H\n" +
	"\rDeleteAccount\x12\x1a.mail.DeleteAccountRequest\x1a\x1b.mail.DeleteAccountResponse\x12=\n" +
	"\rGetStatistics\x12\x1a.mail.GetStatisticsRequest\x1a\x10.mail.StatisticsB7Z5github.com/grigta/conveer/services/mail-service/protob\x06proto3"

var (
	file_services_mail_service_proto_mail_proto_rawDescOnce sync.Once
	file_services_mail_service_proto_mail_proto_rawDescData []byte
)

func file_services_mail_service_proto_mail_proto_rawDescGZIP() []byte {
	file_services_mail_service_proto_mail_proto_rawDescOnce.Do(func() {
		file_services_mail_service_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_mail_service_proto_mail_proto_rawDesc), len(file_services_mail_service_proto_mail_proto_rawDesc)))
	})
	return file_services_mail_service_proto_mail_proto_rawDescData
}

var file_services_mail_service_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_services_mail_service_proto_mail_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),        // 0: mail.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 1: mail.CreateAccountResponse
	(*GetAccountRequest)(nil),           // 2: mail.GetAccountRequest
	(*Account)(nil),                     // 3: mail.Account
	(*ListAccountsRequest)(nil),         // 4: mail.ListAccountsRequest
	(*AccountList)(nil),                 // 5: mail.AccountList
	(*UpdateAccountStatusRequest)(nil),  // 6: mail.UpdateAccountStatusRequest
	(*UpdateAccountStatusResponse)(nil), // 7: mail.UpdateAccountStatusResponse
	(*RetryRegistrationRequest)(nil),    // 8: mail.RetryRegistrationRequest
	(*RetryRegistrationResponse)(nil),   // 9: mail.RetryRegistrationResponse
	(*DeleteAccountRequest)(nil),        // 10: mail.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),       // 11: mail.DeleteAccountResponse
	(*GetStatisticsRequest)(nil),        // 12: mail.GetStatisticsRequest
	(*Statistics)(nil),                  // 13: mail.Statistics
	nil,                                 // 14: mail.Statistics.AccountsByStatusEntry
}
var file_services_mail_service_proto_mail_proto_depIdxs = []int32{
	3,  // 0: mail.AccountList.accounts:type_name -> mail.Account
	14, // 1: mail.Statistics.accounts_by_status:type_name -> mail.Statistics.AccountsByStatusEntry
	0,  // 2: mail.MailService.CreateAccount:input_type -> mail.CreateAccountRequest
	2,  // 3: mail.MailService.GetAccount:input_type -> mail.GetAccountRequest
	4,  // 4: mail.MailService.ListAccounts:input_type -> mail.ListAccountsRequest
	6,  // 5: mail.MailService.UpdateAccountStatus:input_type -> mail.UpdateAccountStatusRequest
	8,  // 6: mail.MailService.RetryRegistration:input_type -> mail.RetryRegistrationRequest
	10, // 7: mail.MailService.DeleteAccount:input_type -> mail.DeleteAccountRequest
	12, // 8: mail.MailService.GetStatistics:input_type -> mail.GetStatisticsRequest
	1,  // 9: mail.MailService.CreateAccount:output_type -> mail.CreateAccountResponse
	3,  // 10: mail.MailService.GetAccount:output_type -> mail.Account
	5,  // 11: mail.MailService.ListAccounts:output_type -> mail.AccountList
	7,  // 12: mail.MailService.UpdateAccountStatus:output_type -> mail.UpdateAccountStatusResponse
	9,  // 13: mail.MailService.RetryRegistration:output_type -> mail.RetryRegistrationResponse
	11, // 14: mail.MailService.DeleteAccount:output_type -> mail.DeleteAccountResponse
	13, // 15: mail.MailService.GetStatistics:output_type -> mail.Statistics
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_services_mail_service_proto_mail_proto_init() }
func file_services_mail_service_proto_mail_proto_init() {
	if File_services_mail_service_proto_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_mail_service_proto_mail_proto_rawDesc), len(file_services_mail_service_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_mail_service_proto_mail_proto_goTypes,
		DependencyIndexes: file_services_mail_service_proto_mail_proto_depIdxs,
		MessageInfos:      file_services_mail_service_proto_mail_proto_msgTypes,
	}.Build()
	File_services_mail_service_proto_mail_proto = out.File
	file_services_mail_service_proto_mail_proto_goTypes = nil
	file_services_mail_service_proto_mail_proto_depIdxs = nil
}
