// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: services/analytics-service/proto/analytics.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetOverallAnalytics_FullMethodName               = "/analytics.AnalyticsService/GetOverallAnalytics"
	AnalyticsService_GetPlatformAnalytics_FullMethodName              = "/analytics.AnalyticsService/GetPlatformAnalytics"
	AnalyticsService_GetExpenseForecast_FullMethodName                = "/analytics.AnalyticsService/GetExpenseForecast"
	AnalyticsService_GetAccountReadinessForecast_FullMethodName       = "/analytics.AnalyticsService/GetAccountReadinessForecast"
	AnalyticsService_GetOptimalRegistrationTime_FullMethodName        = "/analytics.AnalyticsService/GetOptimalRegistrationTime"
	AnalyticsService_GetProxyProviderRankings_FullMethodName          = "/analytics.AnalyticsService/GetProxyProviderRankings"
	AnalyticsService_GetWarmingScenarioRecommendations_FullMethodName = "/analytics.AnalyticsService/GetWarmingScenarioRecommendations"
	AnalyticsService_GetErrorPatternAnalysis_FullMethodName           = "/analytics.AnalyticsService/GetErrorPatternAnalysis"
	AnalyticsService_GetActiveAlerts_FullMethodName                   = "/analytics.AnalyticsService/GetActiveAlerts"
	AnalyticsService_AcknowledgeAlert_FullMethodName                  = "/analytics.AnalyticsService/AcknowledgeAlert"
	AnalyticsService_CreateAlertRule_FullMethodName                   = "/analytics.AnalyticsService/CreateAlertRule"
	AnalyticsService_UpdateAlertRule_FullMethodName                   = "/analytics.AnalyticsService/UpdateAlertRule"
	AnalyticsService_DeleteAlertRule_FullMethodName                   = "/analytics.AnalyticsService/DeleteAlertRule"
	AnalyticsService_ListAlertRules_FullMethodName                    = "/analytics.AnalyticsService/ListAlertRules"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// Получение агрегированной статистики
	GetOverallAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*OverallAnalytics, error)
	GetPlatformAnalytics(ctx context.Context, in *PlatformRequest, opts ...grpc.CallOption) (*PlatformAnalytics, error)
	// Прогнозы
	GetExpenseForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ExpenseForecastResponse, error)
	GetAccountReadinessForecast(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessForecastResponse, error)
	GetOptimalRegistrationTime(ctx context.Context, in *OptimalTimeRequest, opts ...grpc.CallOption) (*OptimalTimeResponse, error)
	// Рекомендации
	GetProxyProviderRankings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProxyRankingsResponse, error)
	GetWarmingScenarioRecommendations(ctx context.Context, in *PlatformRequest, opts ...grpc.CallOption) (*WarmingRecommendationsResponse, error)
	GetErrorPatternAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*ErrorPatternResponse, error)
	// Алерты
	GetActiveAlerts(ctx context.Context, in *AlertsRequest, opts ...grpc.CallOption) (*AlertsResponse, error)
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Управление правилами алертов
	CreateAlertRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*AlertRuleResponse, error)
	UpdateAlertRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*AlertRuleResponse, error)
	DeleteAlertRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListAlertRules(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AlertRulesResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetOverallAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*OverallAnalytics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverallAnalytics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOverallAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPlatformAnalytics(ctx context.Context, in *PlatformRequest, opts ...grpc.CallOption) (*PlatformAnalytics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformAnalytics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPlatformAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetExpenseForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ExpenseForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpenseForecastResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetExpenseForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAccountReadinessForecast(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessForecastResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAccountReadinessForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOptimalRegistrationTime(ctx context.Context, in *OptimalTimeRequest, opts ...grpc.CallOption) (*OptimalTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimalTimeResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOptimalRegistrationTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetProxyProviderRankings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProxyRankingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyRankingsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetProxyProviderRankings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetWarmingScenarioRecommendations(ctx context.Context, in *PlatformRequest, opts ...grpc.CallOption) (*WarmingRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingRecommendationsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetWarmingScenarioRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetErrorPatternAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*ErrorPatternResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorPatternResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetErrorPatternAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetActiveAlerts(ctx context.Context, in *AlertsRequest, opts ...grpc.CallOption) (*AlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetActiveAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, AnalyticsService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) CreateAlertRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*AlertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRuleResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_CreateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) UpdateAlertRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*AlertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRuleResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_UpdateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) DeleteAlertRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, AnalyticsService_DeleteAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ListAlertRules(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AlertRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRulesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ListAlertRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	// Получение агрегированной статистики
	GetOverallAnalytics(context.Context, *AnalyticsRequest) (*OverallAnalytics, error)
	GetPlatformAnalytics(context.Context, *PlatformRequest) (*PlatformAnalytics, error)
	// Прогнозы
	GetExpenseForecast(context.Context, *ForecastRequest) (*ExpenseForecastResponse, error)
	GetAccountReadinessForecast(context.Context, *ReadinessRequest) (*ReadinessForecastResponse, error)
	GetOptimalRegistrationTime(context.Context, *OptimalTimeRequest) (*OptimalTimeResponse, error)
	// Рекомендации
	GetProxyProviderRankings(context.Context, *empty.Empty) (*ProxyRankingsResponse, error)
	GetWarmingScenarioRecommendations(context.Context, *PlatformRequest) (*WarmingRecommendationsResponse, error)
	GetErrorPatternAnalysis(context.Context, *AnalysisRequest) (*ErrorPatternResponse, error)
	// Алерты
	GetActiveAlerts(context.Context, *AlertsRequest) (*AlertsResponse, error)
	AcknowledgeAlert(context.Context, *AcknowledgeRequest) (*empty.Empty, error)
	// Управление правилами алертов
	CreateAlertRule(context.Context, *CreateRuleRequest) (*AlertRuleResponse, error)
	UpdateAlertRule(context.Context, *UpdateRuleRequest) (*AlertRuleResponse, error)
	DeleteAlertRule(context.Context, *DeleteRuleRequest) (*empty.Empty, error)
	ListAlertRules(context.Context, *empty.Empty) (*AlertRulesResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetOverallAnalytics(context.Context, *AnalyticsRequest) (*OverallAnalytics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverallAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPlatformAnalytics(context.Context, *PlatformRequest) (*PlatformAnalytics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetExpenseForecast(context.Context, *ForecastRequest) (*ExpenseForecastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpenseForecast not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAccountReadinessForecast(context.Context, *ReadinessRequest) (*ReadinessForecastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountReadinessForecast not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOptimalRegistrationTime(context.Context, *OptimalTimeRequest) (*OptimalTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOptimalRegistrationTime not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetProxyProviderRankings(context.Context, *empty.Empty) (*ProxyRankingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyProviderRankings not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetWarmingScenarioRecommendations(context.Context, *PlatformRequest) (*WarmingRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarmingScenarioRecommendations not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetErrorPatternAnalysis(context.Context, *AnalysisRequest) (*ErrorPatternResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetErrorPatternAnalysis not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetActiveAlerts(context.Context, *AlertsRequest) (*AlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveAlerts not implemented")
}
func (UnimplementedAnalyticsServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedAnalyticsServiceServer) CreateAlertRule(context.Context, *CreateRuleRequest) (*AlertRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlertRule not implemented")
}
func (UnimplementedAnalyticsServiceServer) UpdateAlertRule(context.Context, *UpdateRuleRequest) (*AlertRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAlertRule not implemented")
}
func (UnimplementedAnalyticsServiceServer) DeleteAlertRule(context.Context, *DeleteRuleRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAlertRule not implemented")
}
func (UnimplementedAnalyticsServiceServer) ListAlertRules(context.Context, *empty.Empty) (*AlertRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlertRules not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetOverallAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOverallAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOverallAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOverallAnalytics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPlatformAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPlatformAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPlatformAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPlatformAnalytics(ctx, req.(*PlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetExpenseForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetExpenseForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetExpenseForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetExpenseForecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAccountReadinessForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAccountReadinessForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAccountReadinessForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAccountReadinessForecast(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOptimalRegistrationTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimalTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOptimalRegistrationTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOptimalRegistrationTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOptimalRegistrationTime(ctx, req.(*OptimalTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetProxyProviderRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetProxyProviderRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetProxyProviderRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetProxyProviderRankings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetWarmingScenarioRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetWarmingScenarioRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetWarmingScenarioRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetWarmingScenarioRecommendations(ctx, req.(*PlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetErrorPatternAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetErrorPatternAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetErrorPatternAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetErrorPatternAnalysis(ctx, req.(*AnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetActiveAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetActiveAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetActiveAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetActiveAlerts(ctx, req.(*AlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_CreateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).CreateAlertRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UpdateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UpdateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_UpdateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UpdateAlertRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_DeleteAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).DeleteAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_DeleteAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).DeleteAlertRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ListAlertRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ListAlertRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ListAlertRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ListAlertRules(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverallAnalytics",
			Handler:    _AnalyticsService_GetOverallAnalytics_Handler,
		},
		{
			MethodName: "GetPlatformAnalytics",
			Handler:    _AnalyticsService_GetPlatformAnalytics_Handler,
		},
		{
			MethodName: "GetExpenseForecast",
			Handler:    _AnalyticsService_GetExpenseForecast_Handler,
		},
		{
			MethodName: "GetAccountReadinessForecast",
			Handler:    _AnalyticsService_GetAccountReadinessForecast_Handler,
		},
		{
			MethodName: "GetOptimalRegistrationTime",
			Handler:    _AnalyticsService_GetOptimalRegistrationTime_Handler,
		},
		{
			MethodName: "GetProxyProviderRankings",
			Handler:    _AnalyticsService_GetProxyProviderRankings_Handler,
		},
		{
			MethodName: "GetWarmingScenarioRecommendations",
			Handler:    _AnalyticsService_GetWarmingScenarioRecommendations_Handler,
		},
		{
			MethodName: "GetErrorPatternAnalysis",
			Handler:    _AnalyticsService_GetErrorPatternAnalysis_Handler,
		},
		{
			MethodName: "GetActiveAlerts",
			Handler:    _AnalyticsService_GetActiveAlerts_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _AnalyticsService_AcknowledgeAlert_Handler,
		},
		{
			MethodName: "CreateAlertRule",
			Handler:    _AnalyticsService_CreateAlertRule_Handler,
		},
		{
			MethodName: "UpdateAlertRule",
			Handler:    _AnalyticsService_UpdateAlertRule_Handler,
		},
		{
			MethodName: "DeleteAlertRule",
			Handler:    _AnalyticsService_DeleteAlertRule_Handler,
		},
		{
			MethodName: "ListAlertRules",
			Handler:    _AnalyticsService_ListAlertRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/analytics-service/proto/analytics.proto",
}
