// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: services/analytics-service/proto/analytics.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsRequest) GetStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *AnalyticsRequest) GetEndDate() *timestamp.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type OverallAnalytics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalAccounts      int64                  `protobuf:"varint,1,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	AccountsByPlatform map[string]int64       `protobuf:"bytes,2,rep,name=accounts_by_platform,json=accountsByPlatform,proto3" json:"accounts_by_platform,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AccountsByStatus   map[string]int64       `protobuf:"bytes,3,rep,name=accounts_by_status,json=accountsByStatus,proto3" json:"accounts_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OverallSuccessRate float64                `protobuf:"fixed64,4,opt,name=overall_success_rate,json=overallSuccessRate,proto3" json:"overall_success_rate,omitempty"`
	OverallBanRate     float64                `protobuf:"fixed64,5,opt,name=overall_ban_rate,json=overallBanRate,proto3" json:"overall_ban_rate,omitempty"`
	Expenses           *ExpensesSummary       `protobuf:"bytes,6,opt,name=expenses,proto3" json:"expenses,omitempty"`
	Resources          *ResourcesSummary      `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	Performance        *PerformanceSummary    `protobuf:"bytes,8,opt,name=performance,proto3" json:"performance,omitempty"`
	Trends             []*TrendData           `protobuf:"bytes,9,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OverallAnalytics) Reset() {
	*x = OverallAnalytics{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallAnalytics) ProtoMessage() {}

func (x *OverallAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallAnalytics.ProtoReflect.Descriptor instead.
func (*OverallAnalytics) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *OverallAnalytics) GetTotalAccounts() int64 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *OverallAnalytics) GetAccountsByPlatform() map[string]int64 {
	if x != nil {
		return x.AccountsByPlatform
	}
	return nil
}

func (x *OverallAnalytics) GetAccountsByStatus() map[string]int64 {
	if x != nil {
		return x.AccountsByStatus
	}
	return nil
}

func (x *OverallAnalytics) GetOverallSuccessRate() float64 {
	if x != nil {
		return x.OverallSuccessRate
	}
	return 0
}

func (x *OverallAnalytics) GetOverallBanRate() float64 {
	if x != nil {
		return x.OverallBanRate
	}
	return 0
}

func (x *OverallAnalytics) GetExpenses() *ExpensesSummary {
	if x != nil {
		return x.Expenses
	}
	return nil
}

func (x *OverallAnalytics) GetResources() *ResourcesSummary {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *OverallAnalytics) GetPerformance() *PerformanceSummary {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *OverallAnalytics) GetTrends() []*TrendData {
	if x != nil {
		return x.Trends
	}
	return nil
}

type ExpensesSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSpentToday   float64                `protobuf:"fixed64,1,opt,name=total_spent_today,json=totalSpentToday,proto3" json:"total_spent_today,omitempty"`
	TotalSpentWeek    float64                `protobuf:"fixed64,2,opt,name=total_spent_week,json=totalSpentWeek,proto3" json:"total_spent_week,omitempty"`
	TotalSpentMonth   float64                `protobuf:"fixed64,3,opt,name=total_spent_month,json=totalSpentMonth,proto3" json:"total_spent_month,omitempty"`
	SmsSpent          float64                `protobuf:"fixed64,4,opt,name=sms_spent,json=smsSpent,proto3" json:"sms_spent,omitempty"`
	ProxySpent        float64                `protobuf:"fixed64,5,opt,name=proxy_spent,json=proxySpent,proto3" json:"proxy_spent,omitempty"`
	AvgCostPerAccount float64                `protobuf:"fixed64,6,opt,name=avg_cost_per_account,json=avgCostPerAccount,proto3" json:"avg_cost_per_account,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExpensesSummary) Reset() {
	*x = ExpensesSummary{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpensesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesSummary) ProtoMessage() {}

func (x *ExpensesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesSummary.ProtoReflect.Descriptor instead.
func (*ExpensesSummary) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ExpensesSummary) GetTotalSpentToday() float64 {
	if x != nil {
		return x.TotalSpentToday
	}
	return 0
}

func (x *ExpensesSummary) GetTotalSpentWeek() float64 {
	if x != nil {
		return x.TotalSpentWeek
	}
	return 0
}

func (x *ExpensesSummary) GetTotalSpentMonth() float64 {
	if x != nil {
		return x.TotalSpentMonth
	}
	return 0
}

func (x *ExpensesSummary) GetSmsSpent() float64 {
	if x != nil {
		return x.SmsSpent
	}
	return 0
}

func (x *ExpensesSummary) GetProxySpent() float64 {
	if x != nil {
		return x.ProxySpent
	}
	return 0
}

func (x *ExpensesSummary) GetAvgCostPerAccount() float64 {
	if x != nil {
		return x.AvgCostPerAccount
	}
	return 0
}

type ResourcesSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveProxies      int64                  `protobuf:"varint,1,opt,name=active_proxies,json=activeProxies,proto3" json:"active_proxies,omitempty"`
	BannedProxies      int64                  `protobuf:"varint,2,opt,name=banned_proxies,json=bannedProxies,proto3" json:"banned_proxies,omitempty"`
	SmsBalance         float64                `protobuf:"fixed64,3,opt,name=sms_balance,json=smsBalance,proto3" json:"sms_balance,omitempty"`
	WarmingTasksActive int64                  `protobuf:"varint,4,opt,name=warming_tasks_active,json=warmingTasksActive,proto3" json:"warming_tasks_active,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourcesSummary) Reset() {
	*x = ResourcesSummary{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesSummary) ProtoMessage() {}

func (x *ResourcesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesSummary.ProtoReflect.Descriptor instead.
func (*ResourcesSummary) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *ResourcesSummary) GetActiveProxies() int64 {
	if x != nil {
		return x.ActiveProxies
	}
	return 0
}

func (x *ResourcesSummary) GetBannedProxies() int64 {
	if x != nil {
		return x.BannedProxies
	}
	return 0
}

func (x *ResourcesSummary) GetSmsBalance() float64 {
	if x != nil {
		return x.SmsBalance
	}
	return 0
}

func (x *ResourcesSummary) GetWarmingTasksActive() int64 {
	if x != nil {
		return x.WarmingTasksActive
	}
	return 0
}

type PerformanceSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AvgWarmingDays       float64                `protobuf:"fixed64,1,opt,name=avg_warming_days,json=avgWarmingDays,proto3" json:"avg_warming_days,omitempty"`
	AccountsCreatedToday int64                  `protobuf:"varint,2,opt,name=accounts_created_today,json=accountsCreatedToday,proto3" json:"accounts_created_today,omitempty"`
	AccountsReadyToday   int64                  `protobuf:"varint,3,opt,name=accounts_ready_today,json=accountsReadyToday,proto3" json:"accounts_ready_today,omitempty"`
	ErrorRate            float64                `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	TopErrors            []*ErrorStat           `protobuf:"bytes,5,rep,name=top_errors,json=topErrors,proto3" json:"top_errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PerformanceSummary) Reset() {
	*x = PerformanceSummary{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceSummary) ProtoMessage() {}

func (x *PerformanceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceSummary.ProtoReflect.Descriptor instead.
func (*PerformanceSummary) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *PerformanceSummary) GetAvgWarmingDays() float64 {
	if x != nil {
		return x.AvgWarmingDays
	}
	return 0
}

func (x *PerformanceSummary) GetAccountsCreatedToday() int64 {
	if x != nil {
		return x.AccountsCreatedToday
	}
	return 0
}

func (x *PerformanceSummary) GetAccountsReadyToday() int64 {
	if x != nil {
		return x.AccountsReadyToday
	}
	return 0
}

func (x *PerformanceSummary) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *PerformanceSummary) GetTopErrors() []*ErrorStat {
	if x != nil {
		return x.TopErrors
	}
	return nil
}

type TrendData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	AccountsCreated int64                  `protobuf:"varint,2,opt,name=accounts_created,json=accountsCreated,proto3" json:"accounts_created,omitempty"`
	AccountsBanned  int64                  `protobuf:"varint,3,opt,name=accounts_banned,json=accountsBanned,proto3" json:"accounts_banned,omitempty"`
	Expenses        float64                `protobuf:"fixed64,4,opt,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrendData) Reset() {
	*x = TrendData{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendData) ProtoMessage() {}

func (x *TrendData) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendData.ProtoReflect.Descriptor instead.
func (*TrendData) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TrendData) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *TrendData) GetAccountsCreated() int64 {
	if x != nil {
		return x.AccountsCreated
	}
	return 0
}

func (x *TrendData) GetAccountsBanned() int64 {
	if x != nil {
		return x.AccountsBanned
	}
	return 0
}

func (x *TrendData) GetExpenses() float64 {
	if x != nil {
		return x.Expenses
	}
	return 0
}

type PlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformRequest) Reset() {
	*x = PlatformRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRequest) ProtoMessage() {}

func (x *PlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRequest.ProtoReflect.Descriptor instead.
func (*PlatformRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *PlatformRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type PlatformAnalytics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Platform        string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	TotalAccounts   int64                  `protobuf:"varint,2,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	ByStatus        map[string]int64       `protobuf:"bytes,3,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SuccessRate     float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	BanRate         float64                `protobuf:"fixed64,5,opt,name=ban_rate,json=banRate,proto3" json:"ban_rate,omitempty"`
	AvgWarmingDays  float64                `protobuf:"fixed64,6,opt,name=avg_warming_days,json=avgWarmingDays,proto3" json:"avg_warming_days,omitempty"`
	TotalSpent      float64                `protobuf:"fixed64,7,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	Recommendations []string               `protobuf:"bytes,8,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlatformAnalytics) Reset() {
	*x = PlatformAnalytics{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformAnalytics) ProtoMessage() {}

func (x *PlatformAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformAnalytics.ProtoReflect.Descriptor instead.
func (*PlatformAnalytics) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *PlatformAnalytics) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformAnalytics) GetTotalAccounts() int64 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *PlatformAnalytics) GetByStatus() map[string]int64 {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

func (x *PlatformAnalytics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *PlatformAnalytics) GetBanRate() float64 {
	if x != nil {
		return x.BanRate
	}
	return 0
}

func (x *PlatformAnalytics) GetAvgWarmingDays() float64 {
	if x != nil {
		return x.AvgWarmingDays
	}
	return 0
}

func (x *PlatformAnalytics) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *PlatformAnalytics) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type ForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastRequest) Reset() {
	*x = ForecastRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastRequest) ProtoMessage() {}

func (x *ForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastRequest.ProtoReflect.Descriptor instead.
func (*ForecastRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ForecastRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type ExpenseForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	PredictedCost float64                `protobuf:"fixed64,2,opt,name=predicted_cost,json=predictedCost,proto3" json:"predicted_cost,omitempty"`
	UpperBound    float64                `protobuf:"fixed64,3,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	LowerBound    float64                `protobuf:"fixed64,4,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	Breakdown     map[string]float64     `protobuf:"bytes,5,rep,name=breakdown,proto3" json:"breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	GeneratedAt   *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseForecastResponse) Reset() {
	*x = ExpenseForecastResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseForecastResponse) ProtoMessage() {}

func (x *ExpenseForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseForecastResponse.ProtoReflect.Descriptor instead.
func (*ExpenseForecastResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *ExpenseForecastResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *ExpenseForecastResponse) GetPredictedCost() float64 {
	if x != nil {
		return x.PredictedCost
	}
	return 0
}

func (x *ExpenseForecastResponse) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *ExpenseForecastResponse) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *ExpenseForecastResponse) GetBreakdown() map[string]float64 {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *ExpenseForecastResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExpenseForecastResponse) GetGeneratedAt() *timestamp.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *ReadinessRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReadinessRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ReadinessForecastResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EstimatedDays   int32                  `protobuf:"varint,2,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	CompletionDate  *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	CurrentProgress float64                `protobuf:"fixed64,4,opt,name=current_progress,json=currentProgress,proto3" json:"current_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadinessForecastResponse) Reset() {
	*x = ReadinessForecastResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessForecastResponse) ProtoMessage() {}

func (x *ReadinessForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessForecastResponse.ProtoReflect.Descriptor instead.
func (*ReadinessForecastResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *ReadinessForecastResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReadinessForecastResponse) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

func (x *ReadinessForecastResponse) GetCompletionDate() *timestamp.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *ReadinessForecastResponse) GetCurrentProgress() float64 {
	if x != nil {
		return x.CurrentProgress
	}
	return 0
}

type OptimalTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimalTimeRequest) Reset() {
	*x = OptimalTimeRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimalTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimalTimeRequest) ProtoMessage() {}

func (x *OptimalTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimalTimeRequest.ProtoReflect.Descriptor instead.
func (*OptimalTimeRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *OptimalTimeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type OptimalTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestHours     []int32                `protobuf:"varint,1,rep,packed,name=best_hours,json=bestHours,proto3" json:"best_hours,omitempty"`
	BestDays      []string               `protobuf:"bytes,2,rep,name=best_days,json=bestDays,proto3" json:"best_days,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	SampleSize    int64                  `protobuf:"varint,4,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimalTimeResponse) Reset() {
	*x = OptimalTimeResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimalTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimalTimeResponse) ProtoMessage() {}

func (x *OptimalTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimalTimeResponse.ProtoReflect.Descriptor instead.
func (*OptimalTimeResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *OptimalTimeResponse) GetBestHours() []int32 {
	if x != nil {
		return x.BestHours
	}
	return nil
}

func (x *OptimalTimeResponse) GetBestDays() []string {
	if x != nil {
		return x.BestDays
	}
	return nil
}

func (x *OptimalTimeResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *OptimalTimeResponse) GetSampleSize() int64 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

type ProxyRankingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rankings      []*ProviderRanking     `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
	GeneratedAt   *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRankingsResponse) Reset() {
	*x = ProxyRankingsResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRankingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRankingsResponse) ProtoMessage() {}

func (x *ProxyRankingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRankingsResponse.ProtoReflect.Descriptor instead.
func (*ProxyRankingsResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyRankingsResponse) GetRankings() []*ProviderRanking {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *ProxyRankingsResponse) GetGeneratedAt() *timestamp.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ProviderRanking struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Score          float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	SuccessRate    float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgLatency     float64                `protobuf:"fixed64,4,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	BanRate        float64                `protobuf:"fixed64,5,opt,name=ban_rate,json=banRate,proto3" json:"ban_rate,omitempty"`
	CostPerAccount float64                `protobuf:"fixed64,6,opt,name=cost_per_account,json=costPerAccount,proto3" json:"cost_per_account,omitempty"`
	Recommendation string                 `protobuf:"bytes,7,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderRanking) Reset() {
	*x = ProviderRanking{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRanking) ProtoMessage() {}

func (x *ProviderRanking) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRanking.ProtoReflect.Descriptor instead.
func (*ProviderRanking) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *ProviderRanking) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderRanking) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProviderRanking) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ProviderRanking) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

func (x *ProviderRanking) GetBanRate() float64 {
	if x != nil {
		return x.BanRate
	}
	return 0
}

func (x *ProviderRanking) GetCostPerAccount() float64 {
	if x != nil {
		return x.CostPerAccount
	}
	return 0
}

func (x *ProviderRanking) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type WarmingRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Platform        string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	RecommendedType string                 `protobuf:"bytes,2,opt,name=recommended_type,json=recommendedType,proto3" json:"recommended_type,omitempty"`
	RecommendedDays int32                  `protobuf:"varint,3,opt,name=recommended_days,json=recommendedDays,proto3" json:"recommended_days,omitempty"`
	SuccessRate     float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	Reasoning       string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WarmingRecommendationsResponse) Reset() {
	*x = WarmingRecommendationsResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmingRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmingRecommendationsResponse) ProtoMessage() {}

func (x *WarmingRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmingRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*WarmingRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *WarmingRecommendationsResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WarmingRecommendationsResponse) GetRecommendedType() string {
	if x != nil {
		return x.RecommendedType
	}
	return ""
}

func (x *WarmingRecommendationsResponse) GetRecommendedDays() int32 {
	if x != nil {
		return x.RecommendedDays
	}
	return 0
}

func (x *WarmingRecommendationsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *WarmingRecommendationsResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *AnalysisRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ErrorPatternResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ErrorCluster        `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPatternResponse) Reset() {
	*x = ErrorPatternResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPatternResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPatternResponse) ProtoMessage() {}

func (x *ErrorPatternResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPatternResponse.ProtoReflect.Descriptor instead.
func (*ErrorPatternResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorPatternResponse) GetClusters() []*ErrorCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ErrorCluster struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Pattern           string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Frequency         int64                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	AffectedPlatforms []string               `protobuf:"bytes,3,rep,name=affected_platforms,json=affectedPlatforms,proto3" json:"affected_platforms,omitempty"`
	RootCause         string                 `protobuf:"bytes,4,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Mitigation        string                 `protobuf:"bytes,5,opt,name=mitigation,proto3" json:"mitigation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ErrorCluster) Reset() {
	*x = ErrorCluster{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCluster) ProtoMessage() {}

func (x *ErrorCluster) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCluster.ProtoReflect.Descriptor instead.
func (*ErrorCluster) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorCluster) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ErrorCluster) GetFrequency() int64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ErrorCluster) GetAffectedPlatforms() []string {
	if x != nil {
		return x.AffectedPlatforms
	}
	return nil
}

func (x *ErrorCluster) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *ErrorCluster) GetMitigation() string {
	if x != nil {
		return x.Mitigation
	}
	return ""
}

type AlertsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UnacknowledgedOnly bool                   `protobuf:"varint,1,opt,name=unacknowledged_only,json=unacknowledgedOnly,proto3" json:"unacknowledged_only,omitempty"`
	Severity           string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AlertsRequest) Reset() {
	*x = AlertsRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertsRequest) ProtoMessage() {}

func (x *AlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertsRequest.ProtoReflect.Descriptor instead.
func (*AlertsRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *AlertsRequest) GetUnacknowledgedOnly() bool {
	if x != nil {
		return x.UnacknowledgedOnly
	}
	return false
}

func (x *AlertsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type AlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*AlertEvent          `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertsResponse) Reset() {
	*x = AlertsResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertsResponse) ProtoMessage() {}

func (x *AlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertsResponse.ProtoReflect.Descriptor instead.
func (*AlertsResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *AlertsResponse) GetAlerts() []*AlertEvent {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type AlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CurrentValue  float64                `protobuf:"fixed64,6,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Threshold     float64                `protobuf:"fixed64,7,opt,name=threshold,proto3" json:"threshold,omitempty"`
	FiredAt       *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=fired_at,json=firedAt,proto3" json:"fired_at,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,9,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *AlertEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertEvent) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *AlertEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertEvent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AlertEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertEvent) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *AlertEvent) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *AlertEvent) GetFiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.FiredAt
	}
	return nil
}

func (x *AlertEvent) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *AcknowledgeRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Threshold     *AlertThreshold        `protobuf:"bytes,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Cooldown      int32                  `protobuf:"varint,6,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRuleRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateRuleRequest) GetThreshold() *AlertThreshold {
	if x != nil {
		return x.Threshold
	}
	return nil
}

func (x *CreateRuleRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateRuleRequest) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Threshold     *AlertThreshold        `protobuf:"bytes,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Cooldown      int32                  `protobuf:"varint,4,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *UpdateRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateRuleRequest) GetThreshold() *AlertThreshold {
	if x != nil {
		return x.Threshold
	}
	return nil
}

func (x *UpdateRuleRequest) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type AlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Threshold     *AlertThreshold        `protobuf:"bytes,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Cooldown      int32                  `protobuf:"varint,8,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRuleResponse) Reset() {
	*x = AlertRuleResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRuleResponse) ProtoMessage() {}

func (x *AlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRuleResponse.ProtoReflect.Descriptor instead.
func (*AlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{27}
}

func (x *AlertRuleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRuleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRuleResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertRuleResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AlertRuleResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRuleResponse) GetThreshold() *AlertThreshold {
	if x != nil {
		return x.Threshold
	}
	return nil
}

func (x *AlertRuleResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRuleResponse) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

type AlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRuleResponse   `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRulesResponse) Reset() {
	*x = AlertRulesResponse{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRulesResponse) ProtoMessage() {}

func (x *AlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRulesResponse.ProtoReflect.Descriptor instead.
func (*AlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{28}
}

func (x *AlertRulesResponse) GetRules() []*AlertRuleResponse {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AlertThreshold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertThreshold) Reset() {
	*x = AlertThreshold{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertThreshold) ProtoMessage() {}

func (x *AlertThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertThreshold.ProtoReflect.Descriptor instead.
func (*AlertThreshold) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{29}
}

func (x *AlertThreshold) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *AlertThreshold) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ErrorStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStat) Reset() {
	*x = ErrorStat{}
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStat) ProtoMessage() {}

func (x *ErrorStat) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_service_proto_analytics_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStat.ProtoReflect.Descriptor instead.
func (*ErrorStat) Descriptor() ([]byte, []int) {
	return file_services_analytics_service_proto_analytics_proto_rawDescGZIP(), []int{30}
}

func (x *ErrorStat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_services_analytics_service_proto_analytics_proto protoreflect.FileDescriptor

const file_services_analytics_service_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"0services/analytics-service/proto/analytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n" +
	"\x10AnalyticsRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xcb\x05\n" +
	"\x10OverallAnalytics\x12%\n" +
	"\x0etotal_accounts\x18\x01 \x01(\x03R\rtotalAccounts\x12e\n" +
	"\x14accounts_by_platform\x18\x02 \x03(\v23.analytics.OverallAnalytics.AccountsByPlatformEntryR\x12accountsByPlatform\x12_\n" +
	"\x12accounts_by_status\x18\x03 \x03(\v21.analytics.OverallAnalytics.AccountsByStatusEntryR\x10accountsByStatus\x120\n" +
	"\x14overall_success_rate\x18\x04 \x01(\x01R\x12overallSuccessRate\x12(\n" +
	"\x10overall_ban_rate\x18\x05 \x01(\x01R\x0eoverallBanRate\x126\n" +
	"\bexpenses\x18\x06 \x01(\v2\x1a.analytics.ExpensesSummaryR\bexpenses\x129\n" +
	"\tresources\x18\a \x01(\v2\x1b.analytics.ResourcesSummaryR\tresources\x12?\n" +
	"\vperformance\x18\b \x01(\v2\x1d.analytics.PerformanceSummaryR\vperformance\x12,\n" +
	"\x06trends\x18\t \x03(\v2\x14.analytics.TrendDataR\x06trends\x1aE\n" +
	"\x17AccountsByPlatformEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15AccountsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x82\x02\n" +
	"\x0fExpensesSummary\x12*\n" +
	"\x11total_spent_today\x18\x01 \x01(\x01R\x0ftotalSpentToday\x12(\n" +
	"\x10total_spent_week\x18\x02 \x01(\x01R\x0etotalSpentWeek\x12*\n" +
	"\x11total_spent_month\x18\x03 \x01(\x01R\x0ftotalSpentMonth\x12\x1b\n" +
	"\tsms_spent\x18\x04 \x01(\x01R\bsmsSpent\x12\x1f\n" +
	"\vproxy_spent\x18\x05 \x01(\x01R\n" +
	"proxySpent\x12/\n" +
	"\x14avg_cost_per_account\x18\x06 \x01(\x01R\x11avgCostPerAccount\"\xb3\x01\n" +
	"\x10ResourcesSummary\x12%\n" +
	"\x0eactive_proxies\x18\x01 \x01(\x03R\ractiveProxies\x12%\n" +
	"\x0ebanned_proxies\x18\x02 \x01(\x03R\rbannedProxies\x12\x1f\n" +
	"\vsms_balance\x18\x03 \x01(\x01R\n" +
	"smsBalance\x120\n" +
	"\x14warming_tasks_active\x18\x04 \x01(\x03R\x12warmingTasksActive\"\xfa\x01\n" +
	"\x12PerformanceSummary\x12(\n" +
	"\x10avg_warming_days\x18\x01 \x01(\x01R\x0eavgWarmingDays\x124\n" +
	"\x16accounts_created_today\x18\x02 \x01(\x03R\x14accountsCreatedToday\x120\n" +
	"\x14accounts_ready_today\x18\x03 \x01(\x03R\x12accountsReadyToday\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x123\n" +
	"\n" +
	"top_errors\x18\x05 \x03(\v2\x14.analytics.ErrorStatR\ttopErrors\"\xab\x01\n" +
	"\tTrendData\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12)\n" +
	"\x10accounts_created\x18\x02 \x01(\x03R\x0faccountsCreated\x12'\n" +
	"\x0faccounts_banned\x18\x03 \x01(\x03R\x0eaccountsBanned\x12\x1a\n" +
	"\bexpenses\x18\x04 \x01(\x01R\bexpenses\"-\n" +
	"\x0fPlatformRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"\x8f\x03\n" +
	"\x11PlatformAnalytics\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12%\n" +
	"\x0etotal_accounts\x18\x02 \x01(\x03R\rtotalAccounts\x12G\n" +
	"\tby_status\x18\x03 \x03(\v2*.analytics.PlatformAnalytics.ByStatusEntryR\bbyStatus\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12\x19\n" +
	"\bban_rate\x18\x05 \x01(\x01R\abanRate\x12(\n" +
	"\x10avg_warming_days\x18\x06 \x01(\x01R\x0eavgWarmingDays\x12\x1f\n" +
	"\vtotal_spent\x18\a \x01(\x01R\n" +
	"totalSpent\x12(\n" +
	"\x0frecommendations\x18\b \x03(\tR\x0frecommendations\x1a;\n" +
	"\rByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\")\n" +
	"\x0fForecastRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"\x88\x03\n" +
	"\x17ExpenseForecastResponse\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12%\n" +
	"\x0epredicted_cost\x18\x02 \x01(\x01R\rpredictedCost\x12\x1f\n" +
	"\vupper_bound\x18\x03 \x01(\x01R\n" +
	"upperBound\x12\x1f\n" +
	"\vlower_bound\x18\x04 \x01(\x01R\n" +
	"lowerBound\x12O\n" +
	"\tbreakdown\x18\x05 \x03(\v21.analytics.ExpenseForecastResponse.BreakdownEntryR\tbreakdown\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x1a<\n" +
	"\x0eBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"M\n" +
	"\x10ReadinessRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"\xd1\x01\n" +
	"\x19ReadinessForecastResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12%\n" +
	"\x0eestimated_days\x18\x02 \x01(\x05R\restimatedDays\x12C\n" +
	"\x0fcompletion_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12)\n" +
	"\x10current_progress\x18\x04 \x01(\x01R\x0fcurrentProgress\"0\n" +
	"\x12OptimalTimeRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"\x95\x01\n" +
	"\x13OptimalTimeResponse\x12\x1d\n" +
	"\n" +
	"best_hours\x18\x01 \x03(\x05R\tbestHours\x12\x1b\n" +
	"\tbest_days\x18\x02 \x03(\tR\bbestDays\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12\x1f\n" +
	"\vsample_size\x18\x04 \x01(\x03R\n" +
	"sampleSize\"\x8e\x01\n" +
	"\x15ProxyRankingsResponse\x126\n" +
	"\brankings\x18\x01 \x03(\v2\x1a.analytics.ProviderRankingR\brankings\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xf4\x01\n" +
	"\x0fProviderRanking\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12\x1f\n" +
	"\vavg_latency\x18\x04 \x01(\x01R\n" +
	"avgLatency\x12\x19\n" +
	"\bban_rate\x18\x05 \x01(\x01R\abanRate\x12(\n" +
	"\x10cost_per_account\x18\x06 \x01(\x01R\x0ecostPerAccount\x12&\n" +
	"\x0erecommendation\x18\a \x01(\tR\x0erecommendation\"\xd3\x01\n" +
	"\x1eWarmingRecommendationsResponse\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12)\n" +
	"\x10recommended_type\x18\x02 \x01(\tR\x0frecommendedType\x12)\n" +
	"\x10recommended_days\x18\x03 \x01(\x05R\x0frecommendedDays\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\"%\n" +
	"\x0fAnalysisRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"K\n" +
	"\x14ErrorPatternResponse\x123\n" +
	"\bclusters\x18\x01 \x03(\v2\x17.analytics.ErrorClusterR\bclusters\"\xb4\x01\n" +
	"\fErrorCluster\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x03R\tfrequency\x12-\n" +
	"\x12affected_platforms\x18\x03 \x03(\tR\x11affectedPlatforms\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x04 \x01(\tR\trootCause\x12\x1e\n" +
	"\n" +
	"mitigation\x18\x05 \x01(\tR\n" +
	"mitigation\"\\\n" +
	"\rAlertsRequest\x12/\n" +
	"\x13unacknowledged_only\x18\x01 \x01(\bR\x12unacknowledgedOnly\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\"?\n" +
	"\x0eAlertsResponse\x12-\n" +
	"\x06alerts\x18\x01 \x03(\v2\x15.analytics.AlertEventR\x06alerts\"\xa9\x02\n" +
	"\n" +
	"AlertEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_value\x18\x06 \x01(\x01R\fcurrentValue\x12\x1c\n" +
	"\tthreshold\x18\a \x01(\x01R\tthreshold\x125\n" +
	"\bfired_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\afiredAt\x12\"\n" +
	"\facknowledged\x18\t \x01(\bR\facknowledged\"/\n" +
	"\x12AcknowledgeRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\"\xc8\x01\n" +
	"\x11CreateRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x127\n" +
	"\tthreshold\x18\x04 \x01(\v2\x19.analytics.AlertThresholdR\tthreshold\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcooldown\x18\x06 \x01(\x05R\bcooldown\"\x9b\x01\n" +
	"\x11UpdateRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x127\n" +
	"\tthreshold\x18\x03 \x01(\v2\x19.analytics.AlertThresholdR\tthreshold\x12\x1a\n" +
	"\bcooldown\x18\x04 \x01(\x05R\bcooldown\",\n" +
	"\x11DeleteRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\xf2\x01\n" +
	"\x11AlertRuleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x127\n" +
	"\tthreshold\x18\x06 \x01(\v2\x19.analytics.AlertThresholdR\tthreshold\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x1a\n" +
	"\bcooldown\x18\b \x01(\x05R\bcooldown\"H\n" +
	"\x12AlertRulesResponse\x122\n" +
	"\x05rules\x18\x01 \x03(\v2\x1c.analytics.AlertRuleResponseR\x05rules\"B\n" +
	"\x0eAlertThreshold\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"5\n" +
	"\tErrorStat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count2\xa7\t\n" +
	"\x10AnalyticsService\x12O\n" +
	"\x13GetOverallAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1b.analytics.OverallAnalytics\x12P\n" +
	"\x14GetPlatformAnalytics\x12\x1a.analytics.PlatformRequest\x1a\x1c.analytics.PlatformAnalytics\x12T\n" +
	"\x12GetExpenseForecast\x12\x1a.analytics.ForecastRequest\x1a\".analytics.ExpenseForecastResponse\x12`\n" +
	"\x1bGetAccountReadinessForecast\x12\x1b.analytics.ReadinessRequest\x1a$.analytics.ReadinessForecastResponse\x12[\n" +
	"\x1aGetOptimalRegistrationTime\x12\x1d.analytics.OptimalTimeRequest\x1a\x1e.analytics.OptimalTimeResponse\x12T\n" +
	"\x18GetProxyProviderRankings\x12\x16.google.protobuf.Empty\x1a .analytics.ProxyRankingsResponse\x12j\n" +
	"!GetWarmingScenarioRecommendations\x12\x1a.analytics.PlatformRequest\x1a).analytics.WarmingRecommendationsResponse\x12V\n" +
	"\x17GetErrorPatternAnalysis\x12\x1a.analytics.AnalysisRequest\x1a\x1f.analytics.ErrorPatternResponse\x12F\n" +
	"\x0fGetActiveAlerts\x12\x18.analytics.AlertsRequest\x1a\x19.analytics.AlertsResponse\x12I\n" +
	"\x10AcknowledgeAlert\x12\x1d.analytics.AcknowledgeRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x0fCreateAlertRule\x12\x1c.analytics.CreateRuleRequest\x1a\x1c.analytics.AlertRuleResponse\x12M\n" +
	"\x0fUpdateAlertRule\x12\x1c.analytics.UpdateRuleRequest\x1a\x1c.analytics.AlertRuleResponse\x12G\n" +
	"\x0fDeleteAlertRule\x12\x1c.analytics.DeleteRuleRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0eListAlertRules\x12\x16.google.protobuf.Empty\x1a\x1d.analytics.AlertRulesResponseB=Z;github.com/conveer/conveer/services/analytics-service/protob\x06proto3"

var (
	file_services_analytics_service_proto_analytics_proto_rawDescOnce sync.Once
	file_services_analytics_service_proto_analytics_proto_rawDescData []byte
)

func file_services_analytics_service_proto_analytics_proto_rawDescGZIP() []byte {
	file_services_analytics_service_proto_analytics_proto_rawDescOnce.Do(func() {
		file_services_analytics_service_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_analytics_service_proto_analytics_proto_rawDesc), len(file_services_analytics_service_proto_analytics_proto_rawDesc)))
	})
	return file_services_analytics_service_proto_analytics_proto_rawDescData
}

var file_services_analytics_service_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_services_analytics_service_proto_analytics_proto_goTypes = []any{
	(*AnalyticsRequest)(nil),               // 0: analytics.AnalyticsRequest
	(*OverallAnalytics)(nil),               // 1: analytics.OverallAnalytics
	(*ExpensesSummary)(nil),                // 2: analytics.ExpensesSummary
	(*ResourcesSummary)(nil),               // 3: analytics.ResourcesSummary
	(*PerformanceSummary)(nil),             // 4: analytics.PerformanceSummary
	(*TrendData)(nil),                      // 5: analytics.TrendData
	(*PlatformRequest)(nil),                // 6: analytics.PlatformRequest
	(*PlatformAnalytics)(nil),              // 7: analytics.PlatformAnalytics
	(*ForecastRequest)(nil),                // 8: analytics.ForecastRequest
	(*ExpenseForecastResponse)(nil),        // 9: analytics.ExpenseForecastResponse
	(*ReadinessRequest)(nil),               // 10: analytics.ReadinessRequest
	(*ReadinessForecastResponse)(nil),      // 11: analytics.ReadinessForecastResponse
	(*OptimalTimeRequest)(nil),             // 12: analytics.OptimalTimeRequest
	(*OptimalTimeResponse)(nil),            // 13: analytics.OptimalTimeResponse
	(*ProxyRankingsResponse)(nil),          // 14: analytics.ProxyRankingsResponse
	(*ProviderRanking)(nil),                // 15: analytics.ProviderRanking
	(*WarmingRecommendationsResponse)(nil), // 16: analytics.WarmingRecommendationsResponse
	(*AnalysisRequest)(nil),                // 17: analytics.AnalysisRequest
	(*ErrorPatternResponse)(nil),           // 18: analytics.ErrorPatternResponse
	(*ErrorCluster)(nil),                   // 19: analytics.ErrorCluster
	(*AlertsRequest)(nil),                  // 20: analytics.AlertsRequest
	(*AlertsResponse)(nil),                 // 21: analytics.AlertsResponse
	(*AlertEvent)(nil),                     // 22: analytics.AlertEvent
	(*AcknowledgeRequest)(nil),             // 23: analytics.AcknowledgeRequest
	(*CreateRuleRequest)(nil),              // 24: analytics.CreateRuleRequest
	(*UpdateRuleRequest)(nil),              // 25: analytics.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),              // 26: analytics.DeleteRuleRequest
	(*AlertRuleResponse)(nil),              // 27: analytics.AlertRuleResponse
	(*AlertRulesResponse)(nil),             // 28: analytics.AlertRulesResponse
	(*AlertThreshold)(nil),                 // 29: analytics.AlertThreshold
	(*ErrorStat)(nil),                      // 30: analytics.ErrorStat
	nil,                                    // 31: analytics.OverallAnalytics.AccountsByPlatformEntry
	nil,                                    // 32: analytics.OverallAnalytics.AccountsByStatusEntry
	nil,                                    // 33: analytics.PlatformAnalytics.ByStatusEntry
	nil,                                    // 34: analytics.ExpenseForecastResponse.BreakdownEntry
	(*timestamp.Timestamp)(nil),            // 35: google.protobuf.Timestamp
	(*empty.Empty)(nil),                    // 36: google.protobuf.Empty
}
var file_services_analytics_service_proto_analytics_proto_depIdxs = []int32{
	35, // 0: analytics.AnalyticsRequest.start_date:type_name -> google.protobuf.Timestamp
	35, // 1: analytics.AnalyticsRequest.end_date:type_name -> google.protobuf.Timestamp
	31, // 2: analytics.OverallAnalytics.accounts_by_platform:type_name -> analytics.OverallAnalytics.AccountsByPlatformEntry
	32, // 3: analytics.OverallAnalytics.accounts_by_status:type_name -> analytics.OverallAnalytics.AccountsByStatusEntry
	2,  // 4: analytics.OverallAnalytics.expenses:type_name -> analytics.ExpensesSummary
	3,  // 5: analytics.OverallAnalytics.resources:type_name -> analytics.ResourcesSummary
	4,  // 6: analytics.OverallAnalytics.performance:type_name -> analytics.PerformanceSummary
	5,  // 7: analytics.OverallAnalytics.trends:type_name -> analytics.TrendData
	30, // 8: analytics.PerformanceSummary.top_errors:type_name -> analytics.ErrorStat
	35, // 9: analytics.TrendData.date:type_name -> google.protobuf.Timestamp
	33, // 10: analytics.PlatformAnalytics.by_status:type_name -> analytics.PlatformAnalytics.ByStatusEntry
	34, // 11: analytics.ExpenseForecastResponse.breakdown:type_name -> analytics.ExpenseForecastResponse.BreakdownEntry
	35, // 12: analytics.ExpenseForecastResponse.generated_at:type_name -> google.protobuf.Timestamp
	35, // 13: analytics.ReadinessForecastResponse.completion_date:type_name -> google.protobuf.Timestamp
	15, // 14: analytics.ProxyRankingsResponse.rankings:type_name -> analytics.ProviderRanking
	35, // 15: analytics.ProxyRankingsResponse.generated_at:type_name -> google.protobuf.Timestamp
	19, // 16: analytics.ErrorPatternResponse.clusters:type_name -> analytics.ErrorCluster
	22, // 17: analytics.AlertsResponse.alerts:type_name -> analytics.AlertEvent
	35, // 18: analytics.AlertEvent.fired_at:type_name -> google.protobuf.Timestamp
	29, // 19: analytics.CreateRuleRequest.threshold:type_name -> analytics.AlertThreshold
	29, // 20: analytics.UpdateRuleRequest.threshold:type_name -> analytics.AlertThreshold
	29, // 21: analytics.AlertRuleResponse.threshold:type_name -> analytics.AlertThreshold
	27, // 22: analytics.AlertRulesResponse.rules:type_name -> analytics.AlertRuleResponse
	0,  // 23: analytics.AnalyticsService.GetOverallAnalytics:input_type -> analytics.AnalyticsRequest
	6,  // 24: analytics.AnalyticsService.GetPlatformAnalytics:input_type -> analytics.PlatformRequest
	8,  // 25: analytics.AnalyticsService.GetExpenseForecast:input_type -> analytics.ForecastRequest
	10, // 26: analytics.AnalyticsService.GetAccountReadinessForecast:input_type -> analytics.ReadinessRequest
	12, // 27: analytics.AnalyticsService.GetOptimalRegistrationTime:input_type -> analytics.OptimalTimeRequest
	36, // 28: analytics.AnalyticsService.GetProxyProviderRankings:input_type -> google.protobuf.Empty
	6,  // 29: analytics.AnalyticsService.GetWarmingScenarioRecommendations:input_type -> analytics.PlatformRequest
	17, // 30: analytics.AnalyticsService.GetErrorPatternAnalysis:input_type -> analytics.AnalysisRequest
	20, // 31: analytics.AnalyticsService.GetActiveAlerts:input_type -> analytics.AlertsRequest
	23, // 32: analytics.AnalyticsService.AcknowledgeAlert:input_type -> analytics.AcknowledgeRequest
	24, // 33: analytics.AnalyticsService.CreateAlertRule:input_type -> analytics.CreateRuleRequest
	25, // 34: analytics.AnalyticsService.UpdateAlertRule:input_type -> analytics.UpdateRuleRequest
	26, // 35: analytics.AnalyticsService.DeleteAlertRule:input_type -> analytics.DeleteRuleRequest
	36, // 36: analytics.AnalyticsService.ListAlertRules:input_type -> google.protobuf.Empty
	1,  // 37: analytics.AnalyticsService.GetOverallAnalytics:output_type -> analytics.OverallAnalytics
	7,  // 38: analytics.AnalyticsService.GetPlatformAnalytics:output_type -> analytics.PlatformAnalytics
	9,  // 39: analytics.AnalyticsService.GetExpenseForecast:output_type -> analytics.ExpenseForecastResponse
	11, // 40: analytics.AnalyticsService.GetAccountReadinessForecast:output_type -> analytics.ReadinessForecastResponse
	13, // 41: analytics.AnalyticsService.GetOptimalRegistrationTime:output_type -> analytics.OptimalTimeResponse
	14, // 42: analytics.AnalyticsService.GetProxyProviderRankings:output_type -> analytics.ProxyRankingsResponse
	16, // 43: analytics.AnalyticsService.GetWarmingScenarioRecommendations:output_type -> analytics.WarmingRecommendationsResponse
	18, // 44: analytics.AnalyticsService.GetErrorPatternAnalysis:output_type -> analytics.ErrorPatternResponse
	21, // 45: analytics.AnalyticsService.GetActiveAlerts:output_type -> analytics.AlertsResponse
	36, // 46: analytics.AnalyticsService.AcknowledgeAlert:output_type -> google.protobuf.Empty
	27, // 47: analytics.AnalyticsService.CreateAlertRule:output_type -> analytics.AlertRuleResponse
	27, // 48: analytics.AnalyticsService.UpdateAlertRule:output_type -> analytics.AlertRuleResponse
	36, // 49: analytics.AnalyticsService.DeleteAlertRule:output_type -> google.protobuf.Empty
	28, // 50: analytics.AnalyticsService.ListAlertRules:output_type -> analytics.AlertRulesResponse
	37, // [37:51] is the sub-list for method output_type
	23, // [23:37] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_services_analytics_service_proto_analytics_proto_init() }
func file_services_analytics_service_proto_analytics_proto_init() {
	if File_services_analytics_service_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_analytics_service_proto_analytics_proto_rawDesc), len(file_services_analytics_service_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_analytics_service_proto_analytics_proto_goTypes,
		DependencyIndexes: file_services_analytics_service_proto_analytics_proto_depIdxs,
		MessageInfos:      file_services_analytics_service_proto_analytics_proto_msgTypes,
	}.Build()
	File_services_analytics_service_proto_analytics_proto = out.File
	file_services_analytics_service_proto_analytics_proto_goTypes = nil
	file_services_analytics_service_proto_analytics_proto_depIdxs = nil
}
