// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: services/sms-service/proto/sms.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseNumberRequest) Reset() {
	*x = PurchaseNumberRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseNumberRequest) ProtoMessage() {}

func (x *PurchaseNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseNumberRequest.ProtoReflect.Descriptor instead.
func (*PurchaseNumberRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseNumberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PurchaseNumberRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PurchaseNumberRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PurchaseNumberRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *PurchaseNumberRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PurchaseNumberRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type PurchaseNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivationId  string                 `protobuf:"bytes,1,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseNumberResponse) Reset() {
	*x = PurchaseNumberResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseNumberResponse) ProtoMessage() {}

func (x *PurchaseNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseNumberResponse.ProtoReflect.Descriptor instead.
func (*PurchaseNumberResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseNumberResponse) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *PurchaseNumberResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PurchaseNumberResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PurchaseNumberResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PurchaseNumberResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PurchaseNumberResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetSMSCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivationId  string                 `protobuf:"bytes,1,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSMSCodeRequest) Reset() {
	*x = GetSMSCodeRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSMSCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSMSCodeRequest) ProtoMessage() {}

func (x *GetSMSCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSMSCodeRequest.ProtoReflect.Descriptor instead.
func (*GetSMSCodeRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{2}
}

func (x *GetSMSCodeRequest) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *GetSMSCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSMSCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	FullSms       string                 `protobuf:"bytes,2,opt,name=full_sms,json=fullSms,proto3" json:"full_sms,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSMSCodeResponse) Reset() {
	*x = GetSMSCodeResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSMSCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSMSCodeResponse) ProtoMessage() {}

func (x *GetSMSCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSMSCodeResponse.ProtoReflect.Descriptor instead.
func (*GetSMSCodeResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{3}
}

func (x *GetSMSCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetSMSCodeResponse) GetFullSms() string {
	if x != nil {
		return x.FullSms
	}
	return ""
}

func (x *GetSMSCodeResponse) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type CancelActivationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivationId  string                 `protobuf:"bytes,1,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActivationRequest) Reset() {
	*x = CancelActivationRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActivationRequest) ProtoMessage() {}

func (x *CancelActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActivationRequest.ProtoReflect.Descriptor instead.
func (*CancelActivationRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{4}
}

func (x *CancelActivationRequest) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *CancelActivationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelActivationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelActivationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Refunded      bool                   `protobuf:"varint,2,opt,name=refunded,proto3" json:"refunded,omitempty"`
	RefundAmount  float32                `protobuf:"fixed32,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActivationResponse) Reset() {
	*x = CancelActivationResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActivationResponse) ProtoMessage() {}

func (x *CancelActivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActivationResponse.ProtoReflect.Descriptor instead.
func (*CancelActivationResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{5}
}

func (x *CancelActivationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelActivationResponse) GetRefunded() bool {
	if x != nil {
		return x.Refunded
	}
	return false
}

func (x *CancelActivationResponse) GetRefundAmount() float32 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

type GetActivationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivationId  string                 `protobuf:"bytes,1,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivationStatusRequest) Reset() {
	*x = GetActivationStatusRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivationStatusRequest) ProtoMessage() {}

func (x *GetActivationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetActivationStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{6}
}

func (x *GetActivationStatusRequest) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *GetActivationStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetActivationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivationId  string                 `protobuf:"bytes,1,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivationStatusResponse) Reset() {
	*x = GetActivationStatusResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivationStatusResponse) ProtoMessage() {}

func (x *GetActivationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetActivationStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{7}
}

func (x *GetActivationStatusResponse) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *GetActivationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetActivationStatusResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetActivationStatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetActivationStatusResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetActivationStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetActivationStatusResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetActivationStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromDate      int64                  `protobuf:"varint,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        int64                  `protobuf:"varint,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatisticsRequest) GetFromDate() int64 {
	if x != nil {
		return x.FromDate
	}
	return 0
}

func (x *GetStatisticsRequest) GetToDate() int64 {
	if x != nil {
		return x.ToDate
	}
	return 0
}

func (x *GetStatisticsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetStatisticsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetStatisticsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalActivations      int32                  `protobuf:"varint,1,opt,name=total_activations,json=totalActivations,proto3" json:"total_activations,omitempty"`
	SuccessfulActivations int32                  `protobuf:"varint,2,opt,name=successful_activations,json=successfulActivations,proto3" json:"successful_activations,omitempty"`
	FailedActivations     int32                  `protobuf:"varint,3,opt,name=failed_activations,json=failedActivations,proto3" json:"failed_activations,omitempty"`
	CancelledActivations  int32                  `protobuf:"varint,4,opt,name=cancelled_activations,json=cancelledActivations,proto3" json:"cancelled_activations,omitempty"`
	TotalSpent            float32                `protobuf:"fixed32,5,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	AveragePrice          float32                `protobuf:"fixed32,6,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	ByService             map[string]int32       `protobuf:"bytes,7,rep,name=by_service,json=byService,proto3" json:"by_service,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByCountry             map[string]int32       `protobuf:"bytes,8,rep,name=by_country,json=byCountry,proto3" json:"by_country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByProvider            map[string]float32     `protobuf:"bytes,9,rep,name=by_provider,json=byProvider,proto3" json:"by_provider,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatisticsResponse) GetTotalActivations() int32 {
	if x != nil {
		return x.TotalActivations
	}
	return 0
}

func (x *GetStatisticsResponse) GetSuccessfulActivations() int32 {
	if x != nil {
		return x.SuccessfulActivations
	}
	return 0
}

func (x *GetStatisticsResponse) GetFailedActivations() int32 {
	if x != nil {
		return x.FailedActivations
	}
	return 0
}

func (x *GetStatisticsResponse) GetCancelledActivations() int32 {
	if x != nil {
		return x.CancelledActivations
	}
	return 0
}

func (x *GetStatisticsResponse) GetTotalSpent() float32 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *GetStatisticsResponse) GetAveragePrice() float32 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *GetStatisticsResponse) GetByService() map[string]int32 {
	if x != nil {
		return x.ByService
	}
	return nil
}

func (x *GetStatisticsResponse) GetByCountry() map[string]int32 {
	if x != nil {
		return x.ByCountry
	}
	return nil
}

func (x *GetStatisticsResponse) GetByProvider() map[string]float32 {
	if x != nil {
		return x.ByProvider
	}
	return nil
}

type GetProviderBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderBalanceRequest) Reset() {
	*x = GetProviderBalanceRequest{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderBalanceRequest) ProtoMessage() {}

func (x *GetProviderBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetProviderBalanceRequest) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{10}
}

func (x *GetProviderBalanceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetProviderBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Balance       float32                `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderBalanceResponse) Reset() {
	*x = GetProviderBalanceResponse{}
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderBalanceResponse) ProtoMessage() {}

func (x *GetProviderBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_sms_service_proto_sms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetProviderBalanceResponse) Descriptor() ([]byte, []int) {
	return file_services_sms_service_proto_sms_proto_rawDescGZIP(), []int{11}
}

func (x *GetProviderBalanceResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetProviderBalanceResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetProviderBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetProviderBalanceResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_services_sms_service_proto_sms_proto protoreflect.FileDescriptor

const file_services_sms_service_proto_sms_proto_rawDesc = "" +
	"\n" +
	"$services/sms-service/proto/sms.proto\x12\x03sms\"\xb9\x01\n" +
	"\x15PurchaseNumberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x05R\bmaxPrice\"\xd4\x01\n" +
	"\x16PurchaseNumberResponse\x12#\n" +
	"\ractivation_id\x18\x01 \x01(\tR\factivationId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"Q\n" +
	"\x11GetSMSCodeRequest\x12#\n" +
	"\ractivation_id\x18\x01 \x01(\tR\factivationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"d\n" +
	"\x12GetSMSCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bfull_sms\x18\x02 \x01(\tR\afullSms\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\x03R\n" +
	"receivedAt\"o\n" +
	"\x17CancelActivationRequest\x12#\n" +
	"\ractivation_id\x18\x01 \x01(\tR\factivationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"u\n" +
	"\x18CancelActivationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\brefunded\x18\x02 \x01(\bR\brefunded\x12#\n" +
	"\rrefund_amount\x18\x03 \x01(\x02R\frefundAmount\"Z\n" +
	"\x1aGetActivationStatusRequest\x12#\n" +
	"\ractivation_id\x18\x01 \x01(\tR\factivationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8c\x02\n" +
	"\x1bGetActivationStatusResponse\x12#\n" +
	"\ractivation_id\x18\x01 \x01(\tR\factivationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\"\x99\x01\n" +
	"\x14GetStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\x03R\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\x03R\x06toDate\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\xc1\x05\n" +
	"\x15GetStatisticsResponse\x12+\n" +
	"\x11total_activations\x18\x01 \x01(\x05R\x10totalActivations\x125\n" +
	"\x16successful_activations\x18\x02 \x01(\x05R\x15successfulActivations\x12-\n" +
	"\x12failed_activations\x18\x03 \x01(\x05R\x11failedActivations\x123\n" +
	"\x15cancelled_activations\x18\x04 \x01(\x05R\x14cancelledActivations\x12\x1f\n" +
	"\vtotal_spent\x18\x05 \x01(\x02R\n" +
	"totalSpent\x12#\n" +
	"\raverage_price\x18\x06 \x01(\x02R\faveragePrice\x12H\n" +
	"\n" +
	"by_service\x18\a \x03(\v2).sms.GetStatisticsResponse.ByServiceEntryR\tbyService\x12H\n" +
	"\n" +
	"by_country\x18\b \x03(\v2).sms.GetStatisticsResponse.ByCountryEntryR\tbyCountry\x12K\n" +
	"\vby_provider\x18\t \x03(\v2*.sms.GetStatisticsResponse.ByProviderEntryR\n" +
	"byProvider\x1a<\n" +
	"\x0eByServiceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eByCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fByProviderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"7\n" +
	"\x19GetProviderBalanceRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\x8d\x01\n" +
	"\x1aGetProviderBalanceResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x02R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt2\xe0\x03\n" +
	"\n" +
	"SMSService\x12I\n" +
	"\x0ePurchaseNumber\x12\x1a.sms.PurchaseNumberRequest\x1a\x1b.sms.PurchaseNumberResponse\x12=\n" +
	"\n" +
	"GetSMSCode\x12\x16.sms.GetSMSCodeRequest\x1a\x17.sms.GetSMSCodeResponse\x12O\n" +
	"\x10CancelActivation\x12\x1c.sms.CancelActivationRequest\x1a\x1d.sms.CancelActivationResponse\x12X\n" +
	"\x13GetActivationStatus\x12\x1f.sms.GetActivationStatusRequest\x1a .sms.GetActivationStatusResponse\x12F\n" +
	"\rGetStatistics\x12\x19.sms.GetStatisticsRequest\x1a\x1a.sms.GetStatisticsResponse\x12U\n" +
	"\x12GetProviderBalance\x12\x1e.sms.GetProviderBalanceRequest\x1a\x1f.sms.GetProviderBalanceResponseB7Z5github.com/conveer/conveer/services/sms-service/protob\x06proto3"

var (
	file_services_sms_service_proto_sms_proto_rawDescOnce sync.Once
	file_services_sms_service_proto_sms_proto_rawDescData []byte
)

func file_services_sms_service_proto_sms_proto_rawDescGZIP() []byte {
	file_services_sms_service_proto_sms_proto_rawDescOnce.Do(func() {
		file_services_sms_service_proto_sms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_sms_service_proto_sms_proto_rawDesc), len(file_services_sms_service_proto_sms_proto_rawDesc)))
	})
	return file_services_sms_service_proto_sms_proto_rawDescData
}

var file_services_sms_service_proto_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_services_sms_service_proto_sms_proto_goTypes = []any{
	(*PurchaseNumberRequest)(nil),       // 0: sms.PurchaseNumberRequest
	(*PurchaseNumberResponse)(nil),      // 1: sms.PurchaseNumberResponse
	(*GetSMSCodeRequest)(nil),           // 2: sms.GetSMSCodeRequest
	(*GetSMSCodeResponse)(nil),          // 3: sms.GetSMSCodeResponse
	(*CancelActivationRequest)(nil),     // 4: sms.CancelActivationRequest
	(*CancelActivationResponse)(nil),    // 5: sms.CancelActivationResponse
	(*GetActivationStatusRequest)(nil),  // 6: sms.GetActivationStatusRequest
	(*GetActivationStatusResponse)(nil), // 7: sms.GetActivationStatusResponse
	(*GetStatisticsRequest)(nil),        // 8: sms.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),       // 9: sms.GetStatisticsResponse
	(*GetProviderBalanceRequest)(nil),   // 10: sms.GetProviderBalanceRequest
	(*GetProviderBalanceResponse)(nil),  // 11: sms.GetProviderBalanceResponse
	nil,                                 // 12: sms.GetStatisticsResponse.ByServiceEntry
	nil,                                 // 13: sms.GetStatisticsResponse.ByCountryEntry
	nil,                                 // 14: sms.GetStatisticsResponse.ByProviderEntry
}
var file_services_sms_service_proto_sms_proto_depIdxs = []int32{
	12, // 0: sms.GetStatisticsResponse.by_service:type_name -> sms.GetStatisticsResponse.ByServiceEntry
	13, // 1: sms.GetStatisticsResponse.by_country:type_name -> sms.GetStatisticsResponse.ByCountryEntry
	14, // 2: sms.GetStatisticsResponse.by_provider:type_name -> sms.GetStatisticsResponse.ByProviderEntry
	0,  // 3: sms.SMSService.PurchaseNumber:input_type -> sms.PurchaseNumberRequest
	2,  // 4: sms.SMSService.GetSMSCode:input_type -> sms.GetSMSCodeRequest
	4,  // 5: sms.SMSService.CancelActivation:input_type -> sms.CancelActivationRequest
	6,  // 6: sms.SMSService.GetActivationStatus:input_type -> sms.GetActivationStatusRequest
	8,  // 7: sms.SMSService.GetStatistics:input_type -> sms.GetStatisticsRequest
	10, // 8: sms.SMSService.GetProviderBalance:input_type -> sms.GetProviderBalanceRequest
	1,  // 9: sms.SMSService.PurchaseNumber:output_type -> sms.PurchaseNumberResponse
	3,  // 10: sms.SMSService.GetSMSCode:output_type -> sms.GetSMSCodeResponse
	5,  // 11: sms.SMSService.CancelActivation:output_type -> sms.CancelActivationResponse
	7,  // 12: sms.SMSService.GetActivationStatus:output_type -> sms.GetActivationStatusResponse
	9,  // 13: sms.SMSService.GetStatistics:output_type -> sms.GetStatisticsResponse
	11, // 14: sms.SMSService.GetProviderBalance:output_type -> sms.GetProviderBalanceResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_sms_service_proto_sms_proto_init() }
func file_services_sms_service_proto_sms_proto_init() {
	if File_services_sms_service_proto_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_sms_service_proto_sms_proto_rawDesc), len(file_services_sms_service_proto_sms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_sms_service_proto_sms_proto_goTypes,
		DependencyIndexes: file_services_sms_service_proto_sms_proto_depIdxs,
		MessageInfos:      file_services_sms_service_proto_sms_proto_msgTypes,
	}.Build()
	File_services_sms_service_proto_sms_proto = out.File
	file_services_sms_service_proto_sms_proto_goTypes = nil
	file_services_sms_service_proto_sms_proto_depIdxs = nil
}
