// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: services/sms-service/proto/sms.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMSService_PurchaseNumber_FullMethodName      = "/sms.SMSService/PurchaseNumber"
	SMSService_GetSMSCode_FullMethodName          = "/sms.SMSService/GetSMSCode"
	SMSService_CancelActivation_FullMethodName    = "/sms.SMSService/CancelActivation"
	SMSService_GetActivationStatus_FullMethodName = "/sms.SMSService/GetActivationStatus"
	SMSService_GetStatistics_FullMethodName       = "/sms.SMSService/GetStatistics"
	SMSService_GetProviderBalance_FullMethodName  = "/sms.SMSService/GetProviderBalance"
)

// SMSServiceClient is the client API for SMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SMSServiceClient interface {
	PurchaseNumber(ctx context.Context, in *PurchaseNumberRequest, opts ...grpc.CallOption) (*PurchaseNumberResponse, error)
	GetSMSCode(ctx context.Context, in *GetSMSCodeRequest, opts ...grpc.CallOption) (*GetSMSCodeResponse, error)
	CancelActivation(ctx context.Context, in *CancelActivationRequest, opts ...grpc.CallOption) (*CancelActivationResponse, error)
	GetActivationStatus(ctx context.Context, in *GetActivationStatusRequest, opts ...grpc.CallOption) (*GetActivationStatusResponse, error)
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
	GetProviderBalance(ctx context.Context, in *GetProviderBalanceRequest, opts ...grpc.CallOption) (*GetProviderBalanceResponse, error)
}

type sMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSMSServiceClient(cc grpc.ClientConnInterface) SMSServiceClient {
	return &sMSServiceClient{cc}
}

func (c *sMSServiceClient) PurchaseNumber(ctx context.Context, in *PurchaseNumberRequest, opts ...grpc.CallOption) (*PurchaseNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseNumberResponse)
	err := c.cc.Invoke(ctx, SMSService_PurchaseNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSServiceClient) GetSMSCode(ctx context.Context, in *GetSMSCodeRequest, opts ...grpc.CallOption) (*GetSMSCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSMSCodeResponse)
	err := c.cc.Invoke(ctx, SMSService_GetSMSCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSServiceClient) CancelActivation(ctx context.Context, in *CancelActivationRequest, opts ...grpc.CallOption) (*CancelActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelActivationResponse)
	err := c.cc.Invoke(ctx, SMSService_CancelActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSServiceClient) GetActivationStatus(ctx context.Context, in *GetActivationStatusRequest, opts ...grpc.CallOption) (*GetActivationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivationStatusResponse)
	err := c.cc.Invoke(ctx, SMSService_GetActivationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, SMSService_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSServiceClient) GetProviderBalance(ctx context.Context, in *GetProviderBalanceRequest, opts ...grpc.CallOption) (*GetProviderBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderBalanceResponse)
	err := c.cc.Invoke(ctx, SMSService_GetProviderBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSServiceServer is the server API for SMSService service.
// All implementations must embed UnimplementedSMSServiceServer
// for forward compatibility.
type SMSServiceServer interface {
	PurchaseNumber(context.Context, *PurchaseNumberRequest) (*PurchaseNumberResponse, error)
	GetSMSCode(context.Context, *GetSMSCodeRequest) (*GetSMSCodeResponse, error)
	CancelActivation(context.Context, *CancelActivationRequest) (*CancelActivationResponse, error)
	GetActivationStatus(context.Context, *GetActivationStatusRequest) (*GetActivationStatusResponse, error)
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	GetProviderBalance(context.Context, *GetProviderBalanceRequest) (*GetProviderBalanceResponse, error)
	mustEmbedUnimplementedSMSServiceServer()
}

// UnimplementedSMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMSServiceServer struct{}

func (UnimplementedSMSServiceServer) PurchaseNumber(context.Context, *PurchaseNumberRequest) (*PurchaseNumberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseNumber not implemented")
}
func (UnimplementedSMSServiceServer) GetSMSCode(context.Context, *GetSMSCodeRequest) (*GetSMSCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSMSCode not implemented")
}
func (UnimplementedSMSServiceServer) CancelActivation(context.Context, *CancelActivationRequest) (*CancelActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelActivation not implemented")
}
func (UnimplementedSMSServiceServer) GetActivationStatus(context.Context, *GetActivationStatusRequest) (*GetActivationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivationStatus not implemented")
}
func (UnimplementedSMSServiceServer) GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedSMSServiceServer) GetProviderBalance(context.Context, *GetProviderBalanceRequest) (*GetProviderBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderBalance not implemented")
}
func (UnimplementedSMSServiceServer) mustEmbedUnimplementedSMSServiceServer() {}
func (UnimplementedSMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMSServiceServer will
// result in compilation errors.
type UnsafeSMSServiceServer interface {
	mustEmbedUnimplementedSMSServiceServer()
}

func RegisterSMSServiceServer(s grpc.ServiceRegistrar, srv SMSServiceServer) {
	// If the following call panics, it indicates UnimplementedSMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMSService_ServiceDesc, srv)
}

func _SMSService_PurchaseNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).PurchaseNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_PurchaseNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).PurchaseNumber(ctx, req.(*PurchaseNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSService_GetSMSCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSMSCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).GetSMSCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_GetSMSCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).GetSMSCode(ctx, req.(*GetSMSCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSService_CancelActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).CancelActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_CancelActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).CancelActivation(ctx, req.(*CancelActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSService_GetActivationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).GetActivationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_GetActivationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).GetActivationStatus(ctx, req.(*GetActivationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSService_GetProviderBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).GetProviderBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSService_GetProviderBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).GetProviderBalance(ctx, req.(*GetProviderBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMSService_ServiceDesc is the grpc.ServiceDesc for SMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.SMSService",
	HandlerType: (*SMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchaseNumber",
			Handler:    _SMSService_PurchaseNumber_Handler,
		},
		{
			MethodName: "GetSMSCode",
			Handler:    _SMSService_GetSMSCode_Handler,
		},
		{
			MethodName: "CancelActivation",
			Handler:    _SMSService_CancelActivation_Handler,
		},
		{
			MethodName: "GetActivationStatus",
			Handler:    _SMSService_GetActivationStatus_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _SMSService_GetStatistics_Handler,
		},
		{
			MethodName: "GetProviderBalance",
			Handler:    _SMSService_GetProviderBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/sms-service/proto/sms.proto",
}
