// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: services/vk-service/proto/vk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FirstName        string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BirthDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender           string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PreferredCountry string                 `protobuf:"bytes,5,opt,name=preferred_country,json=preferredCountry,proto3" json:"preferred_country,omitempty"`
	UseRandomProfile bool                   `protobuf:"varint,6,opt,name=use_random_profile,json=useRandomProfile,proto3" json:"use_random_profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAccountRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *CreateAccountRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateAccountRequest) GetPreferredCountry() string {
	if x != nil {
		return x.PreferredCountry
	}
	return ""
}

func (x *CreateAccountRequest) GetUseRandomProfile() bool {
	if x != nil {
		return x.UseRandomProfile
	}
	return false
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{2}
}

func (x *ListAccountsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAccountsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAccountsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRequest) Reset() {
	*x = RetryRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRequest) ProtoMessage() {}

func (x *RetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRequest.ProtoReflect.Descriptor instead.
func (*RetryRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{4}
}

func (x *RetryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone          string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName      string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username       string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	UserId         string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ProxyId        string                 `protobuf:"bytes,9,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ActivationId   string                 `protobuf:"bytes,10,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	UserAgent      string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Fingerprint    map[string]string      `protobuf:"bytes,12,rep,name=fingerprint,proto3" json:"fingerprint,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegistrationIp string                 `protobuf:"bytes,13,opt,name=registration_ip,json=registrationIp,proto3" json:"registration_ip,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLoginAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,17,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount     int32                  `protobuf:"varint,18,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{6}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Account) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *Account) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

func (x *Account) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Account) GetFingerprint() map[string]string {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *Account) GetRegistrationIp() string {
	if x != nil {
		return x.RegistrationIp
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *Account) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Account) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAccountsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAccountsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Statistics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ByStatus       map[string]int64       `protobuf:"bytes,2,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SuccessRate    float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageRetries float64                `protobuf:"fixed64,4,opt,name=average_retries,json=averageRetries,proto3" json:"average_retries,omitempty"`
	LastHour       int64                  `protobuf:"varint,5,opt,name=last_hour,json=lastHour,proto3" json:"last_hour,omitempty"`
	Last_24Hours   int64                  `protobuf:"varint,6,opt,name=last_24_hours,json=last24Hours,proto3" json:"last_24_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{8}
}

func (x *Statistics) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Statistics) GetByStatus() map[string]int64 {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

func (x *Statistics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *Statistics) GetAverageRetries() float64 {
	if x != nil {
		return x.AverageRetries
	}
	return 0
}

func (x *Statistics) GetLastHour() int64 {
	if x != nil {
		return x.LastHour
	}
	return 0
}

func (x *Statistics) GetLast_24Hours() int64 {
	if x != nil {
		return x.Last_24Hours
	}
	return 0
}

type AccountCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Cookies       string                 `protobuf:"bytes,3,opt,name=cookies,proto3" json:"cookies,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCredentials) Reset() {
	*x = AccountCredentials{}
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCredentials) ProtoMessage() {}

func (x *AccountCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_services_vk_service_proto_vk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCredentials.ProtoReflect.Descriptor instead.
func (*AccountCredentials) Descriptor() ([]byte, []int) {
	return file_services_vk_service_proto_vk_proto_rawDescGZIP(), []int{9}
}

func (x *AccountCredentials) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountCredentials) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *AccountCredentials) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_services_vk_service_proto_vk_proto protoreflect.FileDescriptor

const file_services_vk_service_proto_vk_proto_rawDesc = "" +
	"\n" +
	"\"services/vk-service/proto/vk.proto\x12\x02vk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x80\x02\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x129\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12+\n" +
	"\x11preferred_country\x18\x05 \x01(\tR\x10preferredCountry\x12,\n" +
	"\x12use_random_profile\x18\x06 \x01(\bR\x10useRandomProfile\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"[\n" +
	"\x13ListAccountsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"L\n" +
	"\x13UpdateStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"-\n" +
	"\fRetryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xd2\x05\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x19\n" +
	"\bproxy_id\x18\t \x01(\tR\aproxyId\x12#\n" +
	"\ractivation_id\x18\n" +
	" \x01(\tR\factivationId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12>\n" +
	"\vfingerprint\x18\f \x03(\v2\x1c.vk.Account.FingerprintEntryR\vfingerprint\x12'\n" +
	"\x0fregistration_ip\x18\r \x01(\tR\x0eregistrationIp\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rlast_login_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x12#\n" +
	"\rerror_message\x18\x11 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\x12 \x01(\x05R\n" +
	"retryCount\x1a>\n" +
	"\x10FingerprintEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x14ListAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.vk.AccountR\baccounts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa7\x02\n" +
	"\n" +
	"Statistics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x129\n" +
	"\tby_status\x18\x02 \x03(\v2\x1c.vk.Statistics.ByStatusEntryR\bbyStatus\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12'\n" +
	"\x0faverage_retries\x18\x04 \x01(\x01R\x0eaverageRetries\x12\x1b\n" +
	"\tlast_hour\x18\x05 \x01(\x03R\blastHour\x12\"\n" +
	"\rlast_24_hours\x18\x06 \x01(\x03R\vlast24Hours\x1a;\n" +
	"\rByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8c\x01\n" +
	"\x12AccountCredentials\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acookies\x18\x03 \x01(\tR\acookies\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken2\xed\x03\n" +
	"\tVKService\x126\n" +
	"\rCreateAccount\x12\x18.vk.CreateAccountRequest\x1a\v.vk.Account\x120\n" +
	"\n" +
	"GetAccount\x12\x15.vk.GetAccountRequest\x1a\v.vk.Account\x12F\n" +
	"\x15GetAccountCredentials\x12\x15.vk.GetAccountRequest\x1a\x16.vk.AccountCredentials\x12A\n" +
	"\fListAccounts\x12\x17.vk.ListAccountsRequest\x1a\x18.vk.ListAccountsResponse\x12;\n" +
	"\x13UpdateAccountStatus\x12\x17.vk.UpdateStatusRequest\x1a\v.vk.Account\x122\n" +
	"\x11RetryRegistration\x12\x10.vk.RetryRequest\x1a\v.vk.Account\x12A\n" +
	"\rDeleteAccount\x12\x18.vk.DeleteAccountRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\rGetStatistics\x12\x16.google.protobuf.Empty\x1a\x0e.vk.StatisticsB5Z3github.com/grigta/conveer/services/vk-service/protob\x06proto3"

var (
	file_services_vk_service_proto_vk_proto_rawDescOnce sync.Once
	file_services_vk_service_proto_vk_proto_rawDescData []byte
)

func file_services_vk_service_proto_vk_proto_rawDescGZIP() []byte {
	file_services_vk_service_proto_vk_proto_rawDescOnce.Do(func() {
		file_services_vk_service_proto_vk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_vk_service_proto_vk_proto_rawDesc), len(file_services_vk_service_proto_vk_proto_rawDesc)))
	})
	return file_services_vk_service_proto_vk_proto_rawDescData
}

var file_services_vk_service_proto_vk_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_vk_service_proto_vk_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: vk.CreateAccountRequest
	(*GetAccountRequest)(nil),     // 1: vk.GetAccountRequest
	(*ListAccountsRequest)(nil),   // 2: vk.ListAccountsRequest
	(*UpdateStatusRequest)(nil),   // 3: vk.UpdateStatusRequest
	(*RetryRequest)(nil),          // 4: vk.RetryRequest
	(*DeleteAccountRequest)(nil),  // 5: vk.DeleteAccountRequest
	(*Account)(nil),               // 6: vk.Account
	(*ListAccountsResponse)(nil),  // 7: vk.ListAccountsResponse
	(*Statistics)(nil),            // 8: vk.Statistics
	(*AccountCredentials)(nil),    // 9: vk.AccountCredentials
	nil,                           // 10: vk.Account.FingerprintEntry
	nil,                           // 11: vk.Statistics.ByStatusEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_services_vk_service_proto_vk_proto_depIdxs = []int32{
	12, // 0: vk.CreateAccountRequest.birth_date:type_name -> google.protobuf.Timestamp
	10, // 1: vk.Account.fingerprint:type_name -> vk.Account.FingerprintEntry
	12, // 2: vk.Account.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: vk.Account.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: vk.Account.last_login_at:type_name -> google.protobuf.Timestamp
	6,  // 5: vk.ListAccountsResponse.accounts:type_name -> vk.Account
	11, // 6: vk.Statistics.by_status:type_name -> vk.Statistics.ByStatusEntry
	0,  // 7: vk.VKService.CreateAccount:input_type -> vk.CreateAccountRequest
	1,  // 8: vk.VKService.GetAccount:input_type -> vk.GetAccountRequest
	1,  // 9: vk.VKService.GetAccountCredentials:input_type -> vk.GetAccountRequest
	2,  // 10: vk.VKService.ListAccounts:input_type -> vk.ListAccountsRequest
	3,  // 11: vk.VKService.UpdateAccountStatus:input_type -> vk.UpdateStatusRequest
	4,  // 12: vk.VKService.RetryRegistration:input_type -> vk.RetryRequest
	5,  // 13: vk.VKService.DeleteAccount:input_type -> vk.DeleteAccountRequest
	13, // 14: vk.VKService.GetStatistics:input_type -> google.protobuf.Empty
	6,  // 15: vk.VKService.CreateAccount:output_type -> vk.Account
	6,  // 16: vk.VKService.GetAccount:output_type -> vk.Account
	9,  // 17: vk.VKService.GetAccountCredentials:output_type -> vk.AccountCredentials
	7,  // 18: vk.VKService.ListAccounts:output_type -> vk.ListAccountsResponse
	6,  // 19: vk.VKService.UpdateAccountStatus:output_type -> vk.Account
	6,  // 20: vk.VKService.RetryRegistration:output_type -> vk.Account
	13, // 21: vk.VKService.DeleteAccount:output_type -> google.protobuf.Empty
	8,  // 22: vk.VKService.GetStatistics:output_type -> vk.Statistics
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_vk_service_proto_vk_proto_init() }
func file_services_vk_service_proto_vk_proto_init() {
	if File_services_vk_service_proto_vk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_vk_service_proto_vk_proto_rawDesc), len(file_services_vk_service_proto_vk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_vk_service_proto_vk_proto_goTypes,
		DependencyIndexes: file_services_vk_service_proto_vk_proto_depIdxs,
		MessageInfos:      file_services_vk_service_proto_vk_proto_msgTypes,
	}.Build()
	File_services_vk_service_proto_vk_proto = out.File
	file_services_vk_service_proto_vk_proto_goTypes = nil
	file_services_vk_service_proto_vk_proto_depIdxs = nil
}
