// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: services/warming-service/proto/warming.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartWarmingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                              // "vk", "telegram", "mail", "max"
	ScenarioType  string                 `protobuf:"bytes,3,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"`  // "basic", "advanced", "custom"
	ScenarioId    string                 `protobuf:"bytes,4,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`        // optional, for custom scenarios
	DurationDays  int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"` // 14-30 or 30-60
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWarmingRequest) Reset() {
	*x = StartWarmingRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWarmingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWarmingRequest) ProtoMessage() {}

func (x *StartWarmingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWarmingRequest.ProtoReflect.Descriptor instead.
func (*StartWarmingRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{0}
}

func (x *StartWarmingRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *StartWarmingRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StartWarmingRequest) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

func (x *StartWarmingRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *StartWarmingRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type WarmingTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId        string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Platform         string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ScenarioType     string                 `protobuf:"bytes,4,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"`
	ScenarioId       string                 `protobuf:"bytes,5,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	DurationDays     int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CurrentDay       int32                  `protobuf:"varint,8,opt,name=current_day,json=currentDay,proto3" json:"current_day,omitempty"`
	ActionsCompleted int32                  `protobuf:"varint,9,opt,name=actions_completed,json=actionsCompleted,proto3" json:"actions_completed,omitempty"`
	ActionsFailed    int32                  `protobuf:"varint,10,opt,name=actions_failed,json=actionsFailed,proto3" json:"actions_failed,omitempty"`
	LastError        string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	NextActionAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=next_action_at,json=nextActionAt,proto3" json:"next_action_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WarmingTask) Reset() {
	*x = WarmingTask{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmingTask) ProtoMessage() {}

func (x *WarmingTask) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmingTask.ProtoReflect.Descriptor instead.
func (*WarmingTask) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{2}
}

func (x *WarmingTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WarmingTask) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WarmingTask) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WarmingTask) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

func (x *WarmingTask) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *WarmingTask) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *WarmingTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WarmingTask) GetCurrentDay() int32 {
	if x != nil {
		return x.CurrentDay
	}
	return 0
}

func (x *WarmingTask) GetActionsCompleted() int32 {
	if x != nil {
		return x.ActionsCompleted
	}
	return 0
}

func (x *WarmingTask) GetActionsFailed() int32 {
	if x != nil {
		return x.ActionsFailed
	}
	return 0
}

func (x *WarmingTask) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *WarmingTask) GetNextActionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextActionAt
	}
	return nil
}

func (x *WarmingTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WarmingTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WarmingTask) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type StatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{3}
}

func (x *StatisticsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *StatisticsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *StatisticsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type WarmingStatistics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks      int64                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks  int64                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks     int64                  `protobuf:"varint,3,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	InProgressTasks int64                  `protobuf:"varint,4,opt,name=in_progress_tasks,json=inProgressTasks,proto3" json:"in_progress_tasks,omitempty"`
	SuccessRate     float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgDurationDays float64                `protobuf:"fixed64,6,opt,name=avg_duration_days,json=avgDurationDays,proto3" json:"avg_duration_days,omitempty"`
	ByPlatform      map[string]int64       `protobuf:"bytes,7,rep,name=by_platform,json=byPlatform,proto3" json:"by_platform,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByScenario      map[string]int64       `protobuf:"bytes,8,rep,name=by_scenario,json=byScenario,proto3" json:"by_scenario,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopActions      []*ActionStatistic     `protobuf:"bytes,9,rep,name=top_actions,json=topActions,proto3" json:"top_actions,omitempty"`
	CommonErrors    []*ErrorStatistic      `protobuf:"bytes,10,rep,name=common_errors,json=commonErrors,proto3" json:"common_errors,omitempty"`
	DailyBreakdown  []*DailyStatistic      `protobuf:"bytes,11,rep,name=daily_breakdown,json=dailyBreakdown,proto3" json:"daily_breakdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WarmingStatistics) Reset() {
	*x = WarmingStatistics{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmingStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmingStatistics) ProtoMessage() {}

func (x *WarmingStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmingStatistics.ProtoReflect.Descriptor instead.
func (*WarmingStatistics) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{4}
}

func (x *WarmingStatistics) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *WarmingStatistics) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *WarmingStatistics) GetFailedTasks() int64 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *WarmingStatistics) GetInProgressTasks() int64 {
	if x != nil {
		return x.InProgressTasks
	}
	return 0
}

func (x *WarmingStatistics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *WarmingStatistics) GetAvgDurationDays() float64 {
	if x != nil {
		return x.AvgDurationDays
	}
	return 0
}

func (x *WarmingStatistics) GetByPlatform() map[string]int64 {
	if x != nil {
		return x.ByPlatform
	}
	return nil
}

func (x *WarmingStatistics) GetByScenario() map[string]int64 {
	if x != nil {
		return x.ByScenario
	}
	return nil
}

func (x *WarmingStatistics) GetTopActions() []*ActionStatistic {
	if x != nil {
		return x.TopActions
	}
	return nil
}

func (x *WarmingStatistics) GetCommonErrors() []*ErrorStatistic {
	if x != nil {
		return x.CommonErrors
	}
	return nil
}

func (x *WarmingStatistics) GetDailyBreakdown() []*DailyStatistic {
	if x != nil {
		return x.DailyBreakdown
	}
	return nil
}

type ActionStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgDurationMs float64                `protobuf:"fixed64,4,opt,name=avg_duration_ms,json=avgDurationMs,proto3" json:"avg_duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatistic) Reset() {
	*x = ActionStatistic{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatistic) ProtoMessage() {}

func (x *ActionStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatistic.ProtoReflect.Descriptor instead.
func (*ActionStatistic) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{5}
}

func (x *ActionStatistic) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionStatistic) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ActionStatistic) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ActionStatistic) GetAvgDurationMs() float64 {
	if x != nil {
		return x.AvgDurationMs
	}
	return 0
}

type ErrorStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     string                 `protobuf:"bytes,1,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatistic) Reset() {
	*x = ErrorStatistic{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatistic) ProtoMessage() {}

func (x *ErrorStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatistic.ProtoReflect.Descriptor instead.
func (*ErrorStatistic) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorStatistic) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ErrorStatistic) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ErrorStatistic) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type DailyStatistic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TasksStarted    int64                  `protobuf:"varint,2,opt,name=tasks_started,json=tasksStarted,proto3" json:"tasks_started,omitempty"`
	TasksCompleted  int64                  `protobuf:"varint,3,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	TasksFailed     int64                  `protobuf:"varint,4,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	ActionsExecuted int64                  `protobuf:"varint,5,opt,name=actions_executed,json=actionsExecuted,proto3" json:"actions_executed,omitempty"`
	SuccessRate     float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyStatistic) Reset() {
	*x = DailyStatistic{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatistic) ProtoMessage() {}

func (x *DailyStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatistic.ProtoReflect.Descriptor instead.
func (*DailyStatistic) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{7}
}

func (x *DailyStatistic) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DailyStatistic) GetTasksStarted() int64 {
	if x != nil {
		return x.TasksStarted
	}
	return 0
}

func (x *DailyStatistic) GetTasksCompleted() int64 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *DailyStatistic) GetTasksFailed() int64 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *DailyStatistic) GetActionsExecuted() int64 {
	if x != nil {
		return x.ActionsExecuted
	}
	return 0
}

func (x *DailyStatistic) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type CreateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ActionsJson   string                 `protobuf:"bytes,4,opt,name=actions_json,json=actionsJson,proto3" json:"actions_json,omitempty"`    // JSON-encoded actions config
	ScheduleJson  string                 `protobuf:"bytes,5,opt,name=schedule_json,json=scheduleJson,proto3" json:"schedule_json,omitempty"` // JSON-encoded schedule
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioRequest) Reset() {
	*x = CreateScenarioRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioRequest) ProtoMessage() {}

func (x *CreateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioRequest.ProtoReflect.Descriptor instead.
func (*CreateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{8}
}

func (x *CreateScenarioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScenarioRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScenarioRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateScenarioRequest) GetActionsJson() string {
	if x != nil {
		return x.ActionsJson
	}
	return ""
}

func (x *CreateScenarioRequest) GetScheduleJson() string {
	if x != nil {
		return x.ScheduleJson
	}
	return ""
}

func (x *CreateScenarioRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type UpdateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ActionsJson   string                 `protobuf:"bytes,4,opt,name=actions_json,json=actionsJson,proto3" json:"actions_json,omitempty"`
	ScheduleJson  string                 `protobuf:"bytes,5,opt,name=schedule_json,json=scheduleJson,proto3" json:"schedule_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScenarioRequest) Reset() {
	*x = UpdateScenarioRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioRequest) ProtoMessage() {}

func (x *UpdateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioRequest.ProtoReflect.Descriptor instead.
func (*UpdateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *UpdateScenarioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateScenarioRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScenarioRequest) GetActionsJson() string {
	if x != nil {
		return x.ActionsJson
	}
	return ""
}

func (x *UpdateScenarioRequest) GetScheduleJson() string {
	if x != nil {
		return x.ScheduleJson
	}
	return ""
}

type WarmingScenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmingScenario) Reset() {
	*x = WarmingScenario{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmingScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmingScenario) ProtoMessage() {}

func (x *WarmingScenario) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmingScenario.ProtoReflect.Descriptor instead.
func (*WarmingScenario) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{10}
}

func (x *WarmingScenario) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WarmingScenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WarmingScenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WarmingScenario) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WarmingScenario) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *WarmingScenario) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WarmingScenario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{11}
}

func (x *ListScenariosRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ListScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*WarmingScenario     `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResponse) Reset() {
	*x = ListScenariosResponse{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResponse) ProtoMessage() {}

func (x *ListScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{12}
}

func (x *ListScenariosResponse) GetScenarios() []*WarmingScenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*WarmingTask         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{14}
}

func (x *ListTasksResponse) GetTasks() []*WarmingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ScenarioStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"` // Number of days to look back (default 7)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioStatisticsRequest) Reset() {
	*x = ScenarioStatisticsRequest{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioStatisticsRequest) ProtoMessage() {}

func (x *ScenarioStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioStatisticsRequest.ProtoReflect.Descriptor instead.
func (*ScenarioStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{15}
}

func (x *ScenarioStatisticsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ScenarioStatisticsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ScenarioStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioStats []*ScenarioStats       `protobuf:"bytes,1,rep,name=scenario_stats,json=scenarioStats,proto3" json:"scenario_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioStatisticsResponse) Reset() {
	*x = ScenarioStatisticsResponse{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioStatisticsResponse) ProtoMessage() {}

func (x *ScenarioStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ScenarioStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{16}
}

func (x *ScenarioStatisticsResponse) GetScenarioStats() []*ScenarioStats {
	if x != nil {
		return x.ScenarioStats
	}
	return nil
}

type ScenarioStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioType    string                 `protobuf:"bytes,1,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"` // "basic", "advanced", "custom"
	SuccessRate     float64                `protobuf:"fixed64,2,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgDurationDays float64                `protobuf:"fixed64,3,opt,name=avg_duration_days,json=avgDurationDays,proto3" json:"avg_duration_days,omitempty"`
	CompletedTasks  int64                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks     int64                  `protobuf:"varint,5,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	TotalTasks      int64                  `protobuf:"varint,6,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	Platform        string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScenarioStats) Reset() {
	*x = ScenarioStats{}
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioStats) ProtoMessage() {}

func (x *ScenarioStats) ProtoReflect() protoreflect.Message {
	mi := &file_services_warming_service_proto_warming_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioStats.ProtoReflect.Descriptor instead.
func (*ScenarioStats) Descriptor() ([]byte, []int) {
	return file_services_warming_service_proto_warming_proto_rawDescGZIP(), []int{17}
}

func (x *ScenarioStats) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

func (x *ScenarioStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ScenarioStats) GetAvgDurationDays() float64 {
	if x != nil {
		return x.AvgDurationDays
	}
	return 0
}

func (x *ScenarioStats) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *ScenarioStats) GetFailedTasks() int64 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *ScenarioStats) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *ScenarioStats) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_services_warming_service_proto_warming_proto protoreflect.FileDescriptor

const file_services_warming_service_proto_warming_proto_rawDesc = "" +
	"\n" +
	",services/warming-service/proto/warming.proto\x12\awarming\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x13StartWarmingRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12#\n" +
	"\rscenario_type\x18\x03 \x01(\tR\fscenarioType\x12\x1f\n" +
	"\vscenario_id\x18\x04 \x01(\tR\n" +
	"scenarioId\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\"&\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xe6\x04\n" +
	"\vWarmingTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12#\n" +
	"\rscenario_type\x18\x04 \x01(\tR\fscenarioType\x12\x1f\n" +
	"\vscenario_id\x18\x05 \x01(\tR\n" +
	"scenarioId\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_day\x18\b \x01(\x05R\n" +
	"currentDay\x12+\n" +
	"\x11actions_completed\x18\t \x01(\x05R\x10actionsCompleted\x12%\n" +
	"\x0eactions_failed\x18\n" +
	" \x01(\x05R\ractionsFailed\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x12@\n" +
	"\x0enext_action_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\fnextActionAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa1\x01\n" +
	"\x11StatisticsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xce\x05\n" +
	"\x11WarmingStatistics\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x03R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x03R\x0ecompletedTasks\x12!\n" +
	"\ffailed_tasks\x18\x03 \x01(\x03R\vfailedTasks\x12*\n" +
	"\x11in_progress_tasks\x18\x04 \x01(\x03R\x0finProgressTasks\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x12*\n" +
	"\x11avg_duration_days\x18\x06 \x01(\x01R\x0favgDurationDays\x12K\n" +
	"\vby_platform\x18\a \x03(\v2*.warming.WarmingStatistics.ByPlatformEntryR\n" +
	"byPlatform\x12K\n" +
	"\vby_scenario\x18\b \x03(\v2*.warming.WarmingStatistics.ByScenarioEntryR\n" +
	"byScenario\x129\n" +
	"\vtop_actions\x18\t \x03(\v2\x18.warming.ActionStatisticR\n" +
	"topActions\x12<\n" +
	"\rcommon_errors\x18\n" +
	" \x03(\v2\x17.warming.ErrorStatisticR\fcommonErrors\x12@\n" +
	"\x0fdaily_breakdown\x18\v \x03(\v2\x17.warming.DailyStatisticR\x0edailyBreakdown\x1a=\n" +
	"\x0fByPlatformEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fByScenarioEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x93\x01\n" +
	"\x0fActionStatistic\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12&\n" +
	"\x0favg_duration_ms\x18\x04 \x01(\x01R\ravgDurationMs\"e\n" +
	"\x0eErrorStatistic\x12\x1d\n" +
	"\n" +
	"error_type\x18\x01 \x01(\tR\terrorType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"\xff\x01\n" +
	"\x0eDailyStatistic\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12#\n" +
	"\rtasks_started\x18\x02 \x01(\x03R\ftasksStarted\x12'\n" +
	"\x0ftasks_completed\x18\x03 \x01(\x03R\x0etasksCompleted\x12!\n" +
	"\ftasks_failed\x18\x04 \x01(\x03R\vtasksFailed\x12)\n" +
	"\x10actions_executed\x18\x05 \x01(\x03R\x0factionsExecuted\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\"\xd0\x01\n" +
	"\x15CreateScenarioRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12!\n" +
	"\factions_json\x18\x04 \x01(\tR\vactionsJson\x12#\n" +
	"\rschedule_json\x18\x05 \x01(\tR\fscheduleJson\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\"\xb6\x01\n" +
	"\x15UpdateScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\factions_json\x18\x04 \x01(\tR\vactionsJson\x12#\n" +
	"\rschedule_json\x18\x05 \x01(\tR\fscheduleJson\"\x86\x02\n" +
	"\x0fWarmingScenario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"2\n" +
	"\x14ListScenariosRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"O\n" +
	"\x15ListScenariosResponse\x126\n" +
	"\tscenarios\x18\x01 \x03(\v2\x18.warming.WarmingScenarioR\tscenarios\"\x93\x01\n" +
	"\x10ListTasksRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"`\n" +
	"\x11ListTasksResponse\x12*\n" +
	"\x05tasks\x18\x01 \x03(\v2\x14.warming.WarmingTaskR\x05tasks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"K\n" +
	"\x19ScenarioStatisticsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"[\n" +
	"\x1aScenarioStatisticsResponse\x12=\n" +
	"\x0escenario_stats\x18\x01 \x03(\v2\x16.warming.ScenarioStatsR\rscenarioStats\"\x8c\x02\n" +
	"\rScenarioStats\x12#\n" +
	"\rscenario_type\x18\x01 \x01(\tR\fscenarioType\x12!\n" +
	"\fsuccess_rate\x18\x02 \x01(\x01R\vsuccessRate\x12*\n" +
	"\x11avg_duration_days\x18\x03 \x01(\x01R\x0favgDurationDays\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x03R\x0ecompletedTasks\x12!\n" +
	"\ffailed_tasks\x18\x05 \x01(\x03R\vfailedTasks\x12\x1f\n" +
	"\vtotal_tasks\x18\x06 \x01(\x03R\n" +
	"totalTasks\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform2\xb2\x06\n" +
	"\x0eWarmingService\x12B\n" +
	"\fStartWarming\x12\x1c.warming.StartWarmingRequest\x1a\x14.warming.WarmingTask\x12:\n" +
	"\fPauseWarming\x12\x14.warming.TaskRequest\x1a\x14.warming.WarmingTask\x12;\n" +
	"\rResumeWarming\x12\x14.warming.TaskRequest\x1a\x14.warming.WarmingTask\x129\n" +
	"\vStopWarming\x12\x14.warming.TaskRequest\x1a\x14.warming.WarmingTask\x12>\n" +
	"\x10GetWarmingStatus\x12\x14.warming.TaskRequest\x1a\x14.warming.WarmingTask\x12N\n" +
	"\x14GetWarmingStatistics\x12\x1a.warming.StatisticsRequest\x1a\x1a.warming.WarmingStatistics\x12`\n" +
	"\x15GetScenarioStatistics\x12\".warming.ScenarioStatisticsRequest\x1a#.warming.ScenarioStatisticsResponse\x12P\n" +
	"\x14CreateCustomScenario\x12\x1e.warming.CreateScenarioRequest\x1a\x18.warming.WarmingScenario\x12P\n" +
	"\x14UpdateCustomScenario\x12\x1e.warming.UpdateScenarioRequest\x1a\x18.warming.WarmingScenario\x12N\n" +
	"\rListScenarios\x12\x1d.warming.ListScenariosRequest\x1a\x1e.warming.ListScenariosResponse\x12B\n" +
	"\tListTasks\x12\x19.warming.ListTasksRequest\x1a\x1a.warming.ListTasksResponseB:Z8github.com/grigta/conveer/services/warming-service/protob\x06proto3"

var (
	file_services_warming_service_proto_warming_proto_rawDescOnce sync.Once
	file_services_warming_service_proto_warming_proto_rawDescData []byte
)

func file_services_warming_service_proto_warming_proto_rawDescGZIP() []byte {
	file_services_warming_service_proto_warming_proto_rawDescOnce.Do(func() {
		file_services_warming_service_proto_warming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_warming_service_proto_warming_proto_rawDesc), len(file_services_warming_service_proto_warming_proto_rawDesc)))
	})
	return file_services_warming_service_proto_warming_proto_rawDescData
}

var file_services_warming_service_proto_warming_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_services_warming_service_proto_warming_proto_goTypes = []any{
	(*StartWarmingRequest)(nil),        // 0: warming.StartWarmingRequest
	(*TaskRequest)(nil),                // 1: warming.TaskRequest
	(*WarmingTask)(nil),                // 2: warming.WarmingTask
	(*StatisticsRequest)(nil),          // 3: warming.StatisticsRequest
	(*WarmingStatistics)(nil),          // 4: warming.WarmingStatistics
	(*ActionStatistic)(nil),            // 5: warming.ActionStatistic
	(*ErrorStatistic)(nil),             // 6: warming.ErrorStatistic
	(*DailyStatistic)(nil),             // 7: warming.DailyStatistic
	(*CreateScenarioRequest)(nil),      // 8: warming.CreateScenarioRequest
	(*UpdateScenarioRequest)(nil),      // 9: warming.UpdateScenarioRequest
	(*WarmingScenario)(nil),            // 10: warming.WarmingScenario
	(*ListScenariosRequest)(nil),       // 11: warming.ListScenariosRequest
	(*ListScenariosResponse)(nil),      // 12: warming.ListScenariosResponse
	(*ListTasksRequest)(nil),           // 13: warming.ListTasksRequest
	(*ListTasksResponse)(nil),          // 14: warming.ListTasksResponse
	(*ScenarioStatisticsRequest)(nil),  // 15: warming.ScenarioStatisticsRequest
	(*ScenarioStatisticsResponse)(nil), // 16: warming.ScenarioStatisticsResponse
	(*ScenarioStats)(nil),              // 17: warming.ScenarioStats
	nil,                                // 18: warming.WarmingStatistics.ByPlatformEntry
	nil,                                // 19: warming.WarmingStatistics.ByScenarioEntry
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_services_warming_service_proto_warming_proto_depIdxs = []int32{
	20, // 0: warming.WarmingTask.next_action_at:type_name -> google.protobuf.Timestamp
	20, // 1: warming.WarmingTask.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: warming.WarmingTask.updated_at:type_name -> google.protobuf.Timestamp
	20, // 3: warming.WarmingTask.completed_at:type_name -> google.protobuf.Timestamp
	20, // 4: warming.StatisticsRequest.start_date:type_name -> google.protobuf.Timestamp
	20, // 5: warming.StatisticsRequest.end_date:type_name -> google.protobuf.Timestamp
	18, // 6: warming.WarmingStatistics.by_platform:type_name -> warming.WarmingStatistics.ByPlatformEntry
	19, // 7: warming.WarmingStatistics.by_scenario:type_name -> warming.WarmingStatistics.ByScenarioEntry
	5,  // 8: warming.WarmingStatistics.top_actions:type_name -> warming.ActionStatistic
	6,  // 9: warming.WarmingStatistics.common_errors:type_name -> warming.ErrorStatistic
	7,  // 10: warming.WarmingStatistics.daily_breakdown:type_name -> warming.DailyStatistic
	20, // 11: warming.DailyStatistic.date:type_name -> google.protobuf.Timestamp
	20, // 12: warming.WarmingScenario.created_at:type_name -> google.protobuf.Timestamp
	20, // 13: warming.WarmingScenario.updated_at:type_name -> google.protobuf.Timestamp
	10, // 14: warming.ListScenariosResponse.scenarios:type_name -> warming.WarmingScenario
	2,  // 15: warming.ListTasksResponse.tasks:type_name -> warming.WarmingTask
	17, // 16: warming.ScenarioStatisticsResponse.scenario_stats:type_name -> warming.ScenarioStats
	0,  // 17: warming.WarmingService.StartWarming:input_type -> warming.StartWarmingRequest
	1,  // 18: warming.WarmingService.PauseWarming:input_type -> warming.TaskRequest
	1,  // 19: warming.WarmingService.ResumeWarming:input_type -> warming.TaskRequest
	1,  // 20: warming.WarmingService.StopWarming:input_type -> warming.TaskRequest
	1,  // 21: warming.WarmingService.GetWarmingStatus:input_type -> warming.TaskRequest
	3,  // 22: warming.WarmingService.GetWarmingStatistics:input_type -> warming.StatisticsRequest
	15, // 23: warming.WarmingService.GetScenarioStatistics:input_type -> warming.ScenarioStatisticsRequest
	8,  // 24: warming.WarmingService.CreateCustomScenario:input_type -> warming.CreateScenarioRequest
	9,  // 25: warming.WarmingService.UpdateCustomScenario:input_type -> warming.UpdateScenarioRequest
	11, // 26: warming.WarmingService.ListScenarios:input_type -> warming.ListScenariosRequest
	13, // 27: warming.WarmingService.ListTasks:input_type -> warming.ListTasksRequest
	2,  // 28: warming.WarmingService.StartWarming:output_type -> warming.WarmingTask
	2,  // 29: warming.WarmingService.PauseWarming:output_type -> warming.WarmingTask
	2,  // 30: warming.WarmingService.ResumeWarming:output_type -> warming.WarmingTask
	2,  // 31: warming.WarmingService.StopWarming:output_type -> warming.WarmingTask
	2,  // 32: warming.WarmingService.GetWarmingStatus:output_type -> warming.WarmingTask
	4,  // 33: warming.WarmingService.GetWarmingStatistics:output_type -> warming.WarmingStatistics
	16, // 34: warming.WarmingService.GetScenarioStatistics:output_type -> warming.ScenarioStatisticsResponse
	10, // 35: warming.WarmingService.CreateCustomScenario:output_type -> warming.WarmingScenario
	10, // 36: warming.WarmingService.UpdateCustomScenario:output_type -> warming.WarmingScenario
	12, // 37: warming.WarmingService.ListScenarios:output_type -> warming.ListScenariosResponse
	14, // 38: warming.WarmingService.ListTasks:output_type -> warming.ListTasksResponse
	28, // [28:39] is the sub-list for method output_type
	17, // [17:28] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_services_warming_service_proto_warming_proto_init() }
func file_services_warming_service_proto_warming_proto_init() {
	if File_services_warming_service_proto_warming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_warming_service_proto_warming_proto_rawDesc), len(file_services_warming_service_proto_warming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_warming_service_proto_warming_proto_goTypes,
		DependencyIndexes: file_services_warming_service_proto_warming_proto_depIdxs,
		MessageInfos:      file_services_warming_service_proto_warming_proto_msgTypes,
	}.Build()
	File_services_warming_service_proto_warming_proto = out.File
	file_services_warming_service_proto_warming_proto_goTypes = nil
	file_services_warming_service_proto_warming_proto_depIdxs = nil
}
