// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: services/warming-service/proto/warming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarmingService_StartWarming_FullMethodName          = "/warming.WarmingService/StartWarming"
	WarmingService_PauseWarming_FullMethodName          = "/warming.WarmingService/PauseWarming"
	WarmingService_ResumeWarming_FullMethodName         = "/warming.WarmingService/ResumeWarming"
	WarmingService_StopWarming_FullMethodName           = "/warming.WarmingService/StopWarming"
	WarmingService_GetWarmingStatus_FullMethodName      = "/warming.WarmingService/GetWarmingStatus"
	WarmingService_GetWarmingStatistics_FullMethodName  = "/warming.WarmingService/GetWarmingStatistics"
	WarmingService_GetScenarioStatistics_FullMethodName = "/warming.WarmingService/GetScenarioStatistics"
	WarmingService_CreateCustomScenario_FullMethodName  = "/warming.WarmingService/CreateCustomScenario"
	WarmingService_UpdateCustomScenario_FullMethodName  = "/warming.WarmingService/UpdateCustomScenario"
	WarmingService_ListScenarios_FullMethodName         = "/warming.WarmingService/ListScenarios"
	WarmingService_ListTasks_FullMethodName             = "/warming.WarmingService/ListTasks"
)

// WarmingServiceClient is the client API for WarmingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarmingServiceClient interface {
	StartWarming(ctx context.Context, in *StartWarmingRequest, opts ...grpc.CallOption) (*WarmingTask, error)
	PauseWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error)
	ResumeWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error)
	StopWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error)
	GetWarmingStatus(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error)
	GetWarmingStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*WarmingStatistics, error)
	GetScenarioStatistics(ctx context.Context, in *ScenarioStatisticsRequest, opts ...grpc.CallOption) (*ScenarioStatisticsResponse, error)
	CreateCustomScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*WarmingScenario, error)
	UpdateCustomScenario(ctx context.Context, in *UpdateScenarioRequest, opts ...grpc.CallOption) (*WarmingScenario, error)
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type warmingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarmingServiceClient(cc grpc.ClientConnInterface) WarmingServiceClient {
	return &warmingServiceClient{cc}
}

func (c *warmingServiceClient) StartWarming(ctx context.Context, in *StartWarmingRequest, opts ...grpc.CallOption) (*WarmingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingTask)
	err := c.cc.Invoke(ctx, WarmingService_StartWarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) PauseWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingTask)
	err := c.cc.Invoke(ctx, WarmingService_PauseWarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) ResumeWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingTask)
	err := c.cc.Invoke(ctx, WarmingService_ResumeWarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) StopWarming(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingTask)
	err := c.cc.Invoke(ctx, WarmingService_StopWarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) GetWarmingStatus(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*WarmingTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingTask)
	err := c.cc.Invoke(ctx, WarmingService_GetWarmingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) GetWarmingStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*WarmingStatistics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingStatistics)
	err := c.cc.Invoke(ctx, WarmingService_GetWarmingStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) GetScenarioStatistics(ctx context.Context, in *ScenarioStatisticsRequest, opts ...grpc.CallOption) (*ScenarioStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioStatisticsResponse)
	err := c.cc.Invoke(ctx, WarmingService_GetScenarioStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) CreateCustomScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*WarmingScenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingScenario)
	err := c.cc.Invoke(ctx, WarmingService_CreateCustomScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) UpdateCustomScenario(ctx context.Context, in *UpdateScenarioRequest, opts ...grpc.CallOption) (*WarmingScenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmingScenario)
	err := c.cc.Invoke(ctx, WarmingService_UpdateCustomScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, WarmingService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmingServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, WarmingService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarmingServiceServer is the server API for WarmingService service.
// All implementations must embed UnimplementedWarmingServiceServer
// for forward compatibility.
type WarmingServiceServer interface {
	StartWarming(context.Context, *StartWarmingRequest) (*WarmingTask, error)
	PauseWarming(context.Context, *TaskRequest) (*WarmingTask, error)
	ResumeWarming(context.Context, *TaskRequest) (*WarmingTask, error)
	StopWarming(context.Context, *TaskRequest) (*WarmingTask, error)
	GetWarmingStatus(context.Context, *TaskRequest) (*WarmingTask, error)
	GetWarmingStatistics(context.Context, *StatisticsRequest) (*WarmingStatistics, error)
	GetScenarioStatistics(context.Context, *ScenarioStatisticsRequest) (*ScenarioStatisticsResponse, error)
	CreateCustomScenario(context.Context, *CreateScenarioRequest) (*WarmingScenario, error)
	UpdateCustomScenario(context.Context, *UpdateScenarioRequest) (*WarmingScenario, error)
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	mustEmbedUnimplementedWarmingServiceServer()
}

// UnimplementedWarmingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarmingServiceServer struct{}

func (UnimplementedWarmingServiceServer) StartWarming(context.Context, *StartWarmingRequest) (*WarmingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWarming not implemented")
}
func (UnimplementedWarmingServiceServer) PauseWarming(context.Context, *TaskRequest) (*WarmingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseWarming not implemented")
}
func (UnimplementedWarmingServiceServer) ResumeWarming(context.Context, *TaskRequest) (*WarmingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeWarming not implemented")
}
func (UnimplementedWarmingServiceServer) StopWarming(context.Context, *TaskRequest) (*WarmingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWarming not implemented")
}
func (UnimplementedWarmingServiceServer) GetWarmingStatus(context.Context, *TaskRequest) (*WarmingTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarmingStatus not implemented")
}
func (UnimplementedWarmingServiceServer) GetWarmingStatistics(context.Context, *StatisticsRequest) (*WarmingStatistics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWarmingStatistics not implemented")
}
func (UnimplementedWarmingServiceServer) GetScenarioStatistics(context.Context, *ScenarioStatisticsRequest) (*ScenarioStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScenarioStatistics not implemented")
}
func (UnimplementedWarmingServiceServer) CreateCustomScenario(context.Context, *CreateScenarioRequest) (*WarmingScenario, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomScenario not implemented")
}
func (UnimplementedWarmingServiceServer) UpdateCustomScenario(context.Context, *UpdateScenarioRequest) (*WarmingScenario, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCustomScenario not implemented")
}
func (UnimplementedWarmingServiceServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedWarmingServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedWarmingServiceServer) mustEmbedUnimplementedWarmingServiceServer() {}
func (UnimplementedWarmingServiceServer) testEmbeddedByValue()                        {}

// UnsafeWarmingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarmingServiceServer will
// result in compilation errors.
type UnsafeWarmingServiceServer interface {
	mustEmbedUnimplementedWarmingServiceServer()
}

func RegisterWarmingServiceServer(s grpc.ServiceRegistrar, srv WarmingServiceServer) {
	// If the following call panics, it indicates UnimplementedWarmingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarmingService_ServiceDesc, srv)
}

func _WarmingService_StartWarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWarmingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).StartWarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_StartWarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).StartWarming(ctx, req.(*StartWarmingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_PauseWarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).PauseWarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_PauseWarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).PauseWarming(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_ResumeWarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).ResumeWarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_ResumeWarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).ResumeWarming(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_StopWarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).StopWarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_StopWarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).StopWarming(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_GetWarmingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).GetWarmingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_GetWarmingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).GetWarmingStatus(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_GetWarmingStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).GetWarmingStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_GetWarmingStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).GetWarmingStatistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_GetScenarioStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).GetScenarioStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_GetScenarioStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).GetScenarioStatistics(ctx, req.(*ScenarioStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_CreateCustomScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).CreateCustomScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_CreateCustomScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).CreateCustomScenario(ctx, req.(*CreateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_UpdateCustomScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).UpdateCustomScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_UpdateCustomScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).UpdateCustomScenario(ctx, req.(*UpdateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmingService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmingServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarmingService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmingServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarmingService_ServiceDesc is the grpc.ServiceDesc for WarmingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarmingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warming.WarmingService",
	HandlerType: (*WarmingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWarming",
			Handler:    _WarmingService_StartWarming_Handler,
		},
		{
			MethodName: "PauseWarming",
			Handler:    _WarmingService_PauseWarming_Handler,
		},
		{
			MethodName: "ResumeWarming",
			Handler:    _WarmingService_ResumeWarming_Handler,
		},
		{
			MethodName: "StopWarming",
			Handler:    _WarmingService_StopWarming_Handler,
		},
		{
			MethodName: "GetWarmingStatus",
			Handler:    _WarmingService_GetWarmingStatus_Handler,
		},
		{
			MethodName: "GetWarmingStatistics",
			Handler:    _WarmingService_GetWarmingStatistics_Handler,
		},
		{
			MethodName: "GetScenarioStatistics",
			Handler:    _WarmingService_GetScenarioStatistics_Handler,
		},
		{
			MethodName: "CreateCustomScenario",
			Handler:    _WarmingService_CreateCustomScenario_Handler,
		},
		{
			MethodName: "UpdateCustomScenario",
			Handler:    _WarmingService_UpdateCustomScenario_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _WarmingService_ListScenarios_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _WarmingService_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/warming-service/proto/warming.proto",
}
