// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: services/proxy-service/proto/proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateProxyRequest) Reset() {
	*x = AllocateProxyRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateProxyRequest) ProtoMessage() {}

func (x *AllocateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateProxyRequest.ProtoReflect.Descriptor instead.
func (*AllocateProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateProxyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AllocateProxyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AllocateProxyRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AllocateProxyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ReleaseProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProxyRequest) Reset() {
	*x = ReleaseProxyRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProxyRequest) ProtoMessage() {}

func (x *ReleaseProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProxyRequest.ProtoReflect.Descriptor instead.
func (*ReleaseProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ReleaseProxyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ReleaseProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProxyResponse) Reset() {
	*x = ReleaseProxyResponse{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProxyResponse) ProtoMessage() {}

func (x *ReleaseProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProxyResponse.ProtoReflect.Descriptor instead.
func (*ReleaseProxyResponse) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseProxyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyRequest) Reset() {
	*x = GetProxyRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyRequest) ProtoMessage() {}

func (x *GetProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyRequest.ProtoReflect.Descriptor instead.
func (*GetProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *GetProxyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetProxyHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxyHealthRequest) Reset() {
	*x = GetProxyHealthRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxyHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyHealthRequest) ProtoMessage() {}

func (x *GetProxyHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyHealthRequest.ProtoReflect.Descriptor instead.
func (*GetProxyHealthRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *GetProxyHealthRequest) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

type RotateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateProxyRequest) Reset() {
	*x = RotateProxyRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateProxyRequest) ProtoMessage() {}

func (x *RotateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateProxyRequest.ProtoReflect.Descriptor instead.
func (*RotateProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *RotateProxyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{6}
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Provider      string                 `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *ProxyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ProxyResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProxyResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProxyResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ProxyResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProxyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProxyResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ProxyResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ProxyHealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProxyId         string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Latency         int32                  `protobuf:"varint,2,opt,name=latency,proto3" json:"latency,omitempty"`
	FraudScore      float64                `protobuf:"fixed64,3,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	IsVpn           bool                   `protobuf:"varint,4,opt,name=is_vpn,json=isVpn,proto3" json:"is_vpn,omitempty"`
	IsProxy         bool                   `protobuf:"varint,5,opt,name=is_proxy,json=isProxy,proto3" json:"is_proxy,omitempty"`
	IsTor           bool                   `protobuf:"varint,6,opt,name=is_tor,json=isTor,proto3" json:"is_tor,omitempty"`
	BlacklistStatus bool                   `protobuf:"varint,7,opt,name=blacklist_status,json=blacklistStatus,proto3" json:"blacklist_status,omitempty"`
	LastCheck       int64                  `protobuf:"varint,8,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	FailedChecks    int32                  `protobuf:"varint,9,opt,name=failed_checks,json=failedChecks,proto3" json:"failed_checks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProxyHealthResponse) Reset() {
	*x = ProxyHealthResponse{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHealthResponse) ProtoMessage() {}

func (x *ProxyHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHealthResponse.ProtoReflect.Descriptor instead.
func (*ProxyHealthResponse) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyHealthResponse) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHealthResponse) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ProxyHealthResponse) GetFraudScore() float64 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *ProxyHealthResponse) GetIsVpn() bool {
	if x != nil {
		return x.IsVpn
	}
	return false
}

func (x *ProxyHealthResponse) GetIsProxy() bool {
	if x != nil {
		return x.IsProxy
	}
	return false
}

func (x *ProxyHealthResponse) GetIsTor() bool {
	if x != nil {
		return x.IsTor
	}
	return false
}

func (x *ProxyHealthResponse) GetBlacklistStatus() bool {
	if x != nil {
		return x.BlacklistStatus
	}
	return false
}

func (x *ProxyHealthResponse) GetLastCheck() int64 {
	if x != nil {
		return x.LastCheck
	}
	return 0
}

func (x *ProxyHealthResponse) GetFailedChecks() int32 {
	if x != nil {
		return x.FailedChecks
	}
	return 0
}

type ProxyStatisticsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalProxies     int64                  `protobuf:"varint,1,opt,name=total_proxies,json=totalProxies,proto3" json:"total_proxies,omitempty"`
	ActiveProxies    int64                  `protobuf:"varint,2,opt,name=active_proxies,json=activeProxies,proto3" json:"active_proxies,omitempty"`
	ExpiredProxies   int64                  `protobuf:"varint,3,opt,name=expired_proxies,json=expiredProxies,proto3" json:"expired_proxies,omitempty"`
	BannedProxies    int64                  `protobuf:"varint,4,opt,name=banned_proxies,json=bannedProxies,proto3" json:"banned_proxies,omitempty"`
	TotalBindings    int64                  `protobuf:"varint,5,opt,name=total_bindings,json=totalBindings,proto3" json:"total_bindings,omitempty"`
	ProxiesByType    map[string]int64       `protobuf:"bytes,6,rep,name=proxies_by_type,json=proxiesByType,proto3" json:"proxies_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ProxiesByCountry map[string]int64       `protobuf:"bytes,7,rep,name=proxies_by_country,json=proxiesByCountry,proto3" json:"proxies_by_country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AvgFraudScore    float64                `protobuf:"fixed64,8,opt,name=avg_fraud_score,json=avgFraudScore,proto3" json:"avg_fraud_score,omitempty"`
	AvgLatency       float64                `protobuf:"fixed64,9,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProxyStatisticsResponse) Reset() {
	*x = ProxyStatisticsResponse{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatisticsResponse) ProtoMessage() {}

func (x *ProxyStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ProxyStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyStatisticsResponse) GetTotalProxies() int64 {
	if x != nil {
		return x.TotalProxies
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetActiveProxies() int64 {
	if x != nil {
		return x.ActiveProxies
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetExpiredProxies() int64 {
	if x != nil {
		return x.ExpiredProxies
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetBannedProxies() int64 {
	if x != nil {
		return x.BannedProxies
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetTotalBindings() int64 {
	if x != nil {
		return x.TotalBindings
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetProxiesByType() map[string]int64 {
	if x != nil {
		return x.ProxiesByType
	}
	return nil
}

func (x *ProxyStatisticsResponse) GetProxiesByCountry() map[string]int64 {
	if x != nil {
		return x.ProxiesByCountry
	}
	return nil
}

func (x *ProxyStatisticsResponse) GetAvgFraudScore() float64 {
	if x != nil {
		return x.AvgFraudScore
	}
	return 0
}

func (x *ProxyStatisticsResponse) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

type GetProviderStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"` // Number of days to look back (default 7)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderStatisticsRequest) Reset() {
	*x = GetProviderStatisticsRequest{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderStatisticsRequest) ProtoMessage() {}

func (x *GetProviderStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetProviderStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *GetProviderStatisticsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ProviderStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderStats []*ProviderStats       `protobuf:"bytes,1,rep,name=provider_stats,json=providerStats,proto3" json:"provider_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatisticsResponse) Reset() {
	*x = ProviderStatisticsResponse{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatisticsResponse) ProtoMessage() {}

func (x *ProviderStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ProviderStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderStatisticsResponse) GetProviderStats() []*ProviderStats {
	if x != nil {
		return x.ProviderStats
	}
	return nil
}

type ProviderStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ActiveProxies int64                  `protobuf:"varint,2,opt,name=active_proxies,json=activeProxies,proto3" json:"active_proxies,omitempty"`
	BannedProxies int64                  `protobuf:"varint,3,opt,name=banned_proxies,json=bannedProxies,proto3" json:"banned_proxies,omitempty"`
	AvgLatency    float64                `protobuf:"fixed64,4,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	CostPerProxy  float64                `protobuf:"fixed64,5,opt,name=cost_per_proxy,json=costPerProxy,proto3" json:"cost_per_proxy,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	BanRate       float64                `protobuf:"fixed64,7,opt,name=ban_rate,json=banRate,proto3" json:"ban_rate,omitempty"`
	TotalProxies  int64                  `protobuf:"varint,8,opt,name=total_proxies,json=totalProxies,proto3" json:"total_proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStats) Reset() {
	*x = ProviderStats{}
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStats) ProtoMessage() {}

func (x *ProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_services_proxy_service_proto_proxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStats.ProtoReflect.Descriptor instead.
func (*ProviderStats) Descriptor() ([]byte, []int) {
	return file_services_proxy_service_proto_proxy_proto_rawDescGZIP(), []int{12}
}

func (x *ProviderStats) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderStats) GetActiveProxies() int64 {
	if x != nil {
		return x.ActiveProxies
	}
	return 0
}

func (x *ProviderStats) GetBannedProxies() int64 {
	if x != nil {
		return x.BannedProxies
	}
	return 0
}

func (x *ProviderStats) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

func (x *ProviderStats) GetCostPerProxy() float64 {
	if x != nil {
		return x.CostPerProxy
	}
	return 0
}

func (x *ProviderStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ProviderStats) GetBanRate() float64 {
	if x != nil {
		return x.BanRate
	}
	return 0
}

func (x *ProviderStats) GetTotalProxies() int64 {
	if x != nil {
		return x.TotalProxies
	}
	return 0
}

var File_services_proxy_service_proto_proxy_proto protoreflect.FileDescriptor

const file_services_proxy_service_proto_proxy_proto_rawDesc = "" +
	"\n" +
	"(services/proxy-service/proto/proxy.proto\x12\x05proxy\"\x7f\n" +
	"\x14AllocateProxyRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"4\n" +
	"\x13ReleaseProxyRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"J\n" +
	"\x14ReleaseProxyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x0fGetProxyRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"2\n" +
	"\x15GetProxyHealthRequest\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\"3\n" +
	"\x12RotateProxyRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x16\n" +
	"\x14GetStatisticsRequest\"\xac\x02\n" +
	"\rProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bprovider\"\xa3\x02\n" +
	"\x13ProxyHealthResponse\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x05R\alatency\x12\x1f\n" +
	"\vfraud_score\x18\x03 \x01(\x01R\n" +
	"fraudScore\x12\x15\n" +
	"\x06is_vpn\x18\x04 \x01(\bR\x05isVpn\x12\x19\n" +
	"\bis_proxy\x18\x05 \x01(\bR\aisProxy\x12\x15\n" +
	"\x06is_tor\x18\x06 \x01(\bR\x05isTor\x12)\n" +
	"\x10blacklist_status\x18\a \x01(\bR\x0fblacklistStatus\x12\x1d\n" +
	"\n" +
	"last_check\x18\b \x01(\x03R\tlastCheck\x12#\n" +
	"\rfailed_checks\x18\t \x01(\x05R\ffailedChecks\"\xeb\x04\n" +
	"\x17ProxyStatisticsResponse\x12#\n" +
	"\rtotal_proxies\x18\x01 \x01(\x03R\ftotalProxies\x12%\n" +
	"\x0eactive_proxies\x18\x02 \x01(\x03R\ractiveProxies\x12'\n" +
	"\x0fexpired_proxies\x18\x03 \x01(\x03R\x0eexpiredProxies\x12%\n" +
	"\x0ebanned_proxies\x18\x04 \x01(\x03R\rbannedProxies\x12%\n" +
	"\x0etotal_bindings\x18\x05 \x01(\x03R\rtotalBindings\x12Y\n" +
	"\x0fproxies_by_type\x18\x06 \x03(\v21.proxy.ProxyStatisticsResponse.ProxiesByTypeEntryR\rproxiesByType\x12b\n" +
	"\x12proxies_by_country\x18\a \x03(\v24.proxy.ProxyStatisticsResponse.ProxiesByCountryEntryR\x10proxiesByCountry\x12&\n" +
	"\x0favg_fraud_score\x18\b \x01(\x01R\ravgFraudScore\x12\x1f\n" +
	"\vavg_latency\x18\t \x01(\x01R\n" +
	"avgLatency\x1a@\n" +
	"\x12ProxiesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15ProxiesByCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"2\n" +
	"\x1cGetProviderStatisticsRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"Y\n" +
	"\x1aProviderStatisticsResponse\x12;\n" +
	"\x0eprovider_stats\x18\x01 \x03(\v2\x14.proxy.ProviderStatsR\rproviderStats\"\xa3\x02\n" +
	"\rProviderStats\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12%\n" +
	"\x0eactive_proxies\x18\x02 \x01(\x03R\ractiveProxies\x12%\n" +
	"\x0ebanned_proxies\x18\x03 \x01(\x03R\rbannedProxies\x12\x1f\n" +
	"\vavg_latency\x18\x04 \x01(\x01R\n" +
	"avgLatency\x12$\n" +
	"\x0ecost_per_proxy\x18\x05 \x01(\x01R\fcostPerProxy\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12\x19\n" +
	"\bban_rate\x18\a \x01(\x01R\abanRate\x12#\n" +
	"\rtotal_proxies\x18\b \x01(\x03R\ftotalProxies2\x9f\x04\n" +
	"\fProxyService\x12B\n" +
	"\rAllocateProxy\x12\x1b.proxy.AllocateProxyRequest\x1a\x14.proxy.ProxyResponse\x12G\n" +
	"\fReleaseProxy\x12\x1a.proxy.ReleaseProxyRequest\x1a\x1b.proxy.ReleaseProxyResponse\x12B\n" +
	"\x12GetProxyForAccount\x12\x16.proxy.GetProxyRequest\x1a\x14.proxy.ProxyResponse\x12J\n" +
	"\x0eGetProxyHealth\x12\x1c.proxy.GetProxyHealthRequest\x1a\x1a.proxy.ProxyHealthResponse\x12>\n" +
	"\vRotateProxy\x12\x19.proxy.RotateProxyRequest\x1a\x14.proxy.ProxyResponse\x12Q\n" +
	"\x12GetProxyStatistics\x12\x1b.proxy.GetStatisticsRequest\x1a\x1e.proxy.ProxyStatisticsResponse\x12_\n" +
	"\x15GetProviderStatistics\x12#.proxy.GetProviderStatisticsRequest\x1a!.proxy.ProviderStatisticsResponseB9Z7github.com/conveer/conveer/services/proxy-service/protob\x06proto3"

var (
	file_services_proxy_service_proto_proxy_proto_rawDescOnce sync.Once
	file_services_proxy_service_proto_proxy_proto_rawDescData []byte
)

func file_services_proxy_service_proto_proxy_proto_rawDescGZIP() []byte {
	file_services_proxy_service_proto_proxy_proto_rawDescOnce.Do(func() {
		file_services_proxy_service_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proxy_service_proto_proxy_proto_rawDesc), len(file_services_proxy_service_proto_proxy_proto_rawDesc)))
	})
	return file_services_proxy_service_proto_proxy_proto_rawDescData
}

var file_services_proxy_service_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_services_proxy_service_proto_proxy_proto_goTypes = []any{
	(*AllocateProxyRequest)(nil),         // 0: proxy.AllocateProxyRequest
	(*ReleaseProxyRequest)(nil),          // 1: proxy.ReleaseProxyRequest
	(*ReleaseProxyResponse)(nil),         // 2: proxy.ReleaseProxyResponse
	(*GetProxyRequest)(nil),              // 3: proxy.GetProxyRequest
	(*GetProxyHealthRequest)(nil),        // 4: proxy.GetProxyHealthRequest
	(*RotateProxyRequest)(nil),           // 5: proxy.RotateProxyRequest
	(*GetStatisticsRequest)(nil),         // 6: proxy.GetStatisticsRequest
	(*ProxyResponse)(nil),                // 7: proxy.ProxyResponse
	(*ProxyHealthResponse)(nil),          // 8: proxy.ProxyHealthResponse
	(*ProxyStatisticsResponse)(nil),      // 9: proxy.ProxyStatisticsResponse
	(*GetProviderStatisticsRequest)(nil), // 10: proxy.GetProviderStatisticsRequest
	(*ProviderStatisticsResponse)(nil),   // 11: proxy.ProviderStatisticsResponse
	(*ProviderStats)(nil),                // 12: proxy.ProviderStats
	nil,                                  // 13: proxy.ProxyStatisticsResponse.ProxiesByTypeEntry
	nil,                                  // 14: proxy.ProxyStatisticsResponse.ProxiesByCountryEntry
}
var file_services_proxy_service_proto_proxy_proto_depIdxs = []int32{
	13, // 0: proxy.ProxyStatisticsResponse.proxies_by_type:type_name -> proxy.ProxyStatisticsResponse.ProxiesByTypeEntry
	14, // 1: proxy.ProxyStatisticsResponse.proxies_by_country:type_name -> proxy.ProxyStatisticsResponse.ProxiesByCountryEntry
	12, // 2: proxy.ProviderStatisticsResponse.provider_stats:type_name -> proxy.ProviderStats
	0,  // 3: proxy.ProxyService.AllocateProxy:input_type -> proxy.AllocateProxyRequest
	1,  // 4: proxy.ProxyService.ReleaseProxy:input_type -> proxy.ReleaseProxyRequest
	3,  // 5: proxy.ProxyService.GetProxyForAccount:input_type -> proxy.GetProxyRequest
	4,  // 6: proxy.ProxyService.GetProxyHealth:input_type -> proxy.GetProxyHealthRequest
	5,  // 7: proxy.ProxyService.RotateProxy:input_type -> proxy.RotateProxyRequest
	6,  // 8: proxy.ProxyService.GetProxyStatistics:input_type -> proxy.GetStatisticsRequest
	10, // 9: proxy.ProxyService.GetProviderStatistics:input_type -> proxy.GetProviderStatisticsRequest
	7,  // 10: proxy.ProxyService.AllocateProxy:output_type -> proxy.ProxyResponse
	2,  // 11: proxy.ProxyService.ReleaseProxy:output_type -> proxy.ReleaseProxyResponse
	7,  // 12: proxy.ProxyService.GetProxyForAccount:output_type -> proxy.ProxyResponse
	8,  // 13: proxy.ProxyService.GetProxyHealth:output_type -> proxy.ProxyHealthResponse
	7,  // 14: proxy.ProxyService.RotateProxy:output_type -> proxy.ProxyResponse
	9,  // 15: proxy.ProxyService.GetProxyStatistics:output_type -> proxy.ProxyStatisticsResponse
	11, // 16: proxy.ProxyService.GetProviderStatistics:output_type -> proxy.ProviderStatisticsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_proxy_service_proto_proxy_proto_init() }
func file_services_proxy_service_proto_proxy_proto_init() {
	if File_services_proxy_service_proto_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proxy_service_proto_proxy_proto_rawDesc), len(file_services_proxy_service_proto_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proxy_service_proto_proxy_proto_goTypes,
		DependencyIndexes: file_services_proxy_service_proto_proxy_proto_depIdxs,
		MessageInfos:      file_services_proxy_service_proto_proxy_proto_msgTypes,
	}.Build()
	File_services_proxy_service_proto_proxy_proto = out.File
	file_services_proxy_service_proto_proxy_proto_goTypes = nil
	file_services_proxy_service_proto_proxy_proto_depIdxs = nil
}
