// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: services/proxy-service/proto/proxy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_AllocateProxy_FullMethodName         = "/proxy.ProxyService/AllocateProxy"
	ProxyService_ReleaseProxy_FullMethodName          = "/proxy.ProxyService/ReleaseProxy"
	ProxyService_GetProxyForAccount_FullMethodName    = "/proxy.ProxyService/GetProxyForAccount"
	ProxyService_GetProxyHealth_FullMethodName        = "/proxy.ProxyService/GetProxyHealth"
	ProxyService_RotateProxy_FullMethodName           = "/proxy.ProxyService/RotateProxy"
	ProxyService_GetProxyStatistics_FullMethodName    = "/proxy.ProxyService/GetProxyStatistics"
	ProxyService_GetProviderStatistics_FullMethodName = "/proxy.ProxyService/GetProviderStatistics"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyServiceClient interface {
	AllocateProxy(ctx context.Context, in *AllocateProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
	ReleaseProxy(ctx context.Context, in *ReleaseProxyRequest, opts ...grpc.CallOption) (*ReleaseProxyResponse, error)
	GetProxyForAccount(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
	GetProxyHealth(ctx context.Context, in *GetProxyHealthRequest, opts ...grpc.CallOption) (*ProxyHealthResponse, error)
	RotateProxy(ctx context.Context, in *RotateProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
	GetProxyStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*ProxyStatisticsResponse, error)
	GetProviderStatistics(ctx context.Context, in *GetProviderStatisticsRequest, opts ...grpc.CallOption) (*ProviderStatisticsResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) AllocateProxy(ctx context.Context, in *AllocateProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, ProxyService_AllocateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) ReleaseProxy(ctx context.Context, in *ReleaseProxyRequest, opts ...grpc.CallOption) (*ReleaseProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseProxyResponse)
	err := c.cc.Invoke(ctx, ProxyService_ReleaseProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetProxyForAccount(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, ProxyService_GetProxyForAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetProxyHealth(ctx context.Context, in *GetProxyHealthRequest, opts ...grpc.CallOption) (*ProxyHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyHealthResponse)
	err := c.cc.Invoke(ctx, ProxyService_GetProxyHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) RotateProxy(ctx context.Context, in *RotateProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, ProxyService_RotateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetProxyStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*ProxyStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyStatisticsResponse)
	err := c.cc.Invoke(ctx, ProxyService_GetProxyStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetProviderStatistics(ctx context.Context, in *GetProviderStatisticsRequest, opts ...grpc.CallOption) (*ProviderStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderStatisticsResponse)
	err := c.cc.Invoke(ctx, ProxyService_GetProviderStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
type ProxyServiceServer interface {
	AllocateProxy(context.Context, *AllocateProxyRequest) (*ProxyResponse, error)
	ReleaseProxy(context.Context, *ReleaseProxyRequest) (*ReleaseProxyResponse, error)
	GetProxyForAccount(context.Context, *GetProxyRequest) (*ProxyResponse, error)
	GetProxyHealth(context.Context, *GetProxyHealthRequest) (*ProxyHealthResponse, error)
	RotateProxy(context.Context, *RotateProxyRequest) (*ProxyResponse, error)
	GetProxyStatistics(context.Context, *GetStatisticsRequest) (*ProxyStatisticsResponse, error)
	GetProviderStatistics(context.Context, *GetProviderStatisticsRequest) (*ProviderStatisticsResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) AllocateProxy(context.Context, *AllocateProxyRequest) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateProxy not implemented")
}
func (UnimplementedProxyServiceServer) ReleaseProxy(context.Context, *ReleaseProxyRequest) (*ReleaseProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseProxy not implemented")
}
func (UnimplementedProxyServiceServer) GetProxyForAccount(context.Context, *GetProxyRequest) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyForAccount not implemented")
}
func (UnimplementedProxyServiceServer) GetProxyHealth(context.Context, *GetProxyHealthRequest) (*ProxyHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyHealth not implemented")
}
func (UnimplementedProxyServiceServer) RotateProxy(context.Context, *RotateProxyRequest) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateProxy not implemented")
}
func (UnimplementedProxyServiceServer) GetProxyStatistics(context.Context, *GetStatisticsRequest) (*ProxyStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyStatistics not implemented")
}
func (UnimplementedProxyServiceServer) GetProviderStatistics(context.Context, *GetProviderStatisticsRequest) (*ProviderStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderStatistics not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_AllocateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).AllocateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_AllocateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).AllocateProxy(ctx, req.(*AllocateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_ReleaseProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).ReleaseProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_ReleaseProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).ReleaseProxy(ctx, req.(*ReleaseProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetProxyForAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetProxyForAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetProxyForAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetProxyForAccount(ctx, req.(*GetProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetProxyHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetProxyHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetProxyHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetProxyHealth(ctx, req.(*GetProxyHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_RotateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).RotateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_RotateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).RotateProxy(ctx, req.(*RotateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetProxyStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetProxyStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetProxyStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetProxyStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetProviderStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetProviderStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetProviderStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetProviderStatistics(ctx, req.(*GetProviderStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateProxy",
			Handler:    _ProxyService_AllocateProxy_Handler,
		},
		{
			MethodName: "ReleaseProxy",
			Handler:    _ProxyService_ReleaseProxy_Handler,
		},
		{
			MethodName: "GetProxyForAccount",
			Handler:    _ProxyService_GetProxyForAccount_Handler,
		},
		{
			MethodName: "GetProxyHealth",
			Handler:    _ProxyService_GetProxyHealth_Handler,
		},
		{
			MethodName: "RotateProxy",
			Handler:    _ProxyService_RotateProxy_Handler,
		},
		{
			MethodName: "GetProxyStatistics",
			Handler:    _ProxyService_GetProxyStatistics_Handler,
		},
		{
			MethodName: "GetProviderStatistics",
			Handler:    _ProxyService_GetProviderStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/proxy-service/proto/proxy.proto",
}
